package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for Automation entity
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public final class AutomationSql {

    public static final String FIND_ALL = """
        SELECT action_type, created_at, archived, target_entity_type, created_by, trigger_details, modified_at, modified_by, id, trigger_type, action_details, type
        FROM automations
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM automations
        """;

    public static final String FIND_BY_ID = """
        SELECT action_type, created_at, archived, target_entity_type, created_by, trigger_details, modified_at, modified_by, id, trigger_type, action_details, type
        FROM automations
        WHERE id = :id
        """;

    public static final String INSERT = """
        INSERT INTO automations (action_type, created_at, archived, target_entity_type, created_by, trigger_details, modified_at, modified_by, trigger_type, action_details, type)
        VALUES (:actionType, :createdAt, :archived, :targetEntityType, :createdBy, :triggerDetails::jsonb, :modifiedAt, :modifiedBy, :triggerType, :actionDetails::jsonb, :type)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE automations SET
            action_type = :actionType,
            created_at = :createdAt,
            archived = :archived,
            target_entity_type = :targetEntityType,
            created_by = :createdBy,
            trigger_details = :triggerDetails::jsonb,
            modified_at = :modifiedAt,
            modified_by = :modifiedBy,
            trigger_type = :triggerType,
            action_details = :actionDetails::jsonb,
            type = :type
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM automations
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM automations
        WHERE id = :id
        """;

    private AutomationSql() {
        // Utility class
    }
}
