package com.example.daoGenerator.dao.sql;

/**
 * SQL constants for ClientCredentials entity
 * Generated by JDBC DAO Generator
 */
public final class ClientCredentialsSql {

    public static final String FIND_BY_ID = """
        SELECT archived, client_name, client_description, client_secret, id
        FROM client_credentials
        WHERE id = :id
        """;

    public static final String FIND_ALL = """
        SELECT archived, client_name, client_description, client_secret, id
        FROM client_credentials
        """;

    public static final String INSERT = """
        INSERT INTO client_credentials (archived, client_name, client_description, client_secret)
        VALUES (:archived, :clientName, :clientDescription, :clientSecret)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE client_credentials SET
            archived = :archived,
            client_name = :clientName,
            client_description = :clientDescription,
            client_secret = :clientSecret
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM client_credentials
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM client_credentials
        WHERE id = :id
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM client_credentials
        """;

    private ClientCredentialsSql() {
        // Utility class
    }
}
