package com.example.daoGenerator.dao.sql;

/**
 * SQL constants for EmailTemplates entity
 * Generated by JDBC DAO Generator
 */
public final class EmailTemplatesSql {

    public static final String FIND_BY_ID = """
        SELECT archived, name, id, content
        FROM email_templates
        WHERE id = :id
        """;

    public static final String FIND_ALL = """
        SELECT archived, name, id, content
        FROM email_templates
        """;

    public static final String INSERT = """
        INSERT INTO email_templates (archived, name, content)
        VALUES (:archived, :name, :content)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE email_templates SET
            archived = :archived,
            name = :name,
            content = :content
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM email_templates
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM email_templates
        WHERE id = :id
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM email_templates
        """;

    private EmailTemplatesSql() {
        // Utility class
    }
}
