package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for EmailTemplate entity
 * Key Type: NO_PRIMARY_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public final class EmailTemplateSql {

    public static final String FIND_ALL = """
        SELECT archived, name, id, content
        FROM email_templates
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM email_templates
        """;

    public static final String INSERT = """
        INSERT INTO email_templates (archived, name, id, content)
        VALUES (:archived, :name, :id, :content)
        """;

    private EmailTemplateSql() {
        // Utility class
    }
}
