package com.example.daoGenerator.dao.sql;

/**
 * SQL constants for Interlocks entity
 * Generated by JDBC DAO Generator
 */
public final class InterlocksSql {

    public static final String FIND_BY_ID = """
        SELECT target_entity_id, created_at, target_entity_type, created_by, modified_at, modified_by, id, validations
        FROM interlocks
        WHERE id = :id
        """;

    public static final String FIND_ALL = """
        SELECT target_entity_id, created_at, target_entity_type, created_by, modified_at, modified_by, id, validations
        FROM interlocks
        """;

    public static final String INSERT = """
        INSERT INTO interlocks (target_entity_id, created_at, target_entity_type, created_by, modified_at, modified_by, validations)
        VALUES (:targetEntityId, :createdAt, :targetEntityType, :createdBy, :modifiedAt, :modifiedBy, :validations::jsonb)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE interlocks SET
            target_entity_id = :targetEntityId,
            created_at = :createdAt,
            target_entity_type = :targetEntityType,
            created_by = :createdBy,
            modified_at = :modifiedAt,
            modified_by = :modifiedBy,
            validations = :validations::jsonb
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM interlocks
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM interlocks
        WHERE id = :id
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM interlocks
        """;

    public static final String FIND_BY_TARGET_ENTITY_ID = """
        SELECT target_entity_id, created_at, target_entity_type, created_by, modified_at, modified_by, id, validations
        FROM interlocks
        WHERE target_entity_id = :targetEntityId
        """;

    private InterlocksSql() {
        // Utility class
    }
}
