package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for JobAudit entity
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public final class JobAuditSql {

    public static final String FIND_ALL = """
        SELECT organisations_id, tasks_id, action, details, id, stages_id, triggered_at, jobs_id, parameters, triggered_by
        FROM job_audits
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM job_audits
        """;

    public static final String FIND_BY_ID = """
        SELECT organisations_id, tasks_id, action, details, id, stages_id, triggered_at, jobs_id, parameters, triggered_by
        FROM job_audits
        WHERE id = :id
        """;

    public static final String INSERT = """
        INSERT INTO job_audits (organisations_id, tasks_id, action, details, stages_id, triggered_at, jobs_id, parameters, triggered_by)
        VALUES (:organisationsId, :tasksId, :action, :details, :stagesId, :triggeredAt, :jobsId, :parameters::jsonb, :triggeredBy)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE job_audits SET
            organisations_id = :organisationsId,
            tasks_id = :tasksId,
            action = :action,
            details = :details,
            stages_id = :stagesId,
            triggered_at = :triggeredAt,
            jobs_id = :jobsId,
            parameters = :parameters::jsonb,
            triggered_by = :triggeredBy
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM job_audits
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM job_audits
        WHERE id = :id
        """;

    private JobAuditSql() {
        // Utility class
    }
}
