package com.example.daoGenerator.dao.sql;

/**
 * SQL constants for JobPropertyValues entity
 * Generated by JDBC DAO Generator
 */
public final class JobPropertyValuesSql {

    public static final String FIND_BY_ID = """
        SELECT created_at, created_by, modified_at, modified_by, facility_use_case_property_mapping_id, value, jobs_id
        FROM job_property_values
        WHERE id = :id
        """;

    public static final String FIND_ALL = """
        SELECT created_at, created_by, modified_at, modified_by, facility_use_case_property_mapping_id, value, jobs_id
        FROM job_property_values
        """;

    public static final String INSERT = """
        INSERT INTO job_property_values (created_at, created_by, modified_at, modified_by, facility_use_case_property_mapping_id, value, jobs_id)
        VALUES (:createdAt, :createdBy, :modifiedAt, :modifiedBy, :facilityUseCasePropertyMappingId, :value, :jobsId)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE job_property_values SET
            created_at = :createdAt,
            created_by = :createdBy,
            modified_at = :modifiedAt,
            modified_by = :modifiedBy,
            facility_use_case_property_mapping_id = :facilityUseCasePropertyMappingId,
            value = :value,
            jobs_id = :jobsId
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM job_property_values
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM job_property_values
        WHERE id = :id
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM job_property_values
        """;

    public static final String FIND_BY_FACILITY_USE_CASE_PROPERTY_MAPPING_ID = """
        SELECT created_at, created_by, modified_at, modified_by, facility_use_case_property_mapping_id, value, jobs_id
        FROM job_property_values
        WHERE facility_use_case_property_mapping_id = :facilityUseCasePropertyMappingId
        """;

    public static final String FIND_BY_MODIFIED_BY = """
        SELECT created_at, created_by, modified_at, modified_by, facility_use_case_property_mapping_id, value, jobs_id
        FROM job_property_values
        WHERE modified_by = :modifiedBy
        """;

    public static final String FIND_BY_JOBS_ID = """
        SELECT created_at, created_by, modified_at, modified_by, facility_use_case_property_mapping_id, value, jobs_id
        FROM job_property_values
        WHERE jobs_id = :jobsId
        """;

    public static final String FIND_BY_CREATED_BY = """
        SELECT created_at, created_by, modified_at, modified_by, facility_use_case_property_mapping_id, value, jobs_id
        FROM job_property_values
        WHERE created_by = :createdBy
        """;

    private JobPropertyValuesSql() {
        // Utility class
    }
}
