package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for ParameterValues entity
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public final class ParameterValuesSql {

    public static final String FIND_ALL = """
        SELECT reason, has_corrections, hidden, modified_at, verified, parameters_id, client_epoch, has_active_exception, version, created_at, created_by, has_variations, impacted_by, modified_by, id, state, task_executions_id, choices, has_exceptions, value, jobs_id, parameter_value_approval_id
        FROM parameter_values
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM parameter_values
        """;

    public static final String FIND_BY_ID = """
        SELECT reason, has_corrections, hidden, modified_at, verified, parameters_id, client_epoch, has_active_exception, version, created_at, created_by, has_variations, impacted_by, modified_by, id, state, task_executions_id, choices, has_exceptions, value, jobs_id, parameter_value_approval_id
        FROM parameter_values
        WHERE id = :id
        """;

    public static final String INSERT = """
        INSERT INTO parameter_values (reason, has_corrections, hidden, modified_at, verified, parameters_id, client_epoch, has_active_exception, version, created_at, created_by, has_variations, impacted_by, modified_by, state, task_executions_id, choices, has_exceptions, value, jobs_id, parameter_value_approval_id)
        VALUES (:reason, :hasCorrections, :hidden, :modifiedAt, :verified, :parametersId, :clientEpoch, :hasActiveException, :version, :createdAt, :createdBy, :hasVariations, :impactedBy::jsonb, :modifiedBy, :state, :taskExecutionsId, :choices::jsonb, :hasExceptions, :value, :jobsId, :parameterValueApprovalId)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE parameter_values SET
            reason = :reason,
            has_corrections = :hasCorrections,
            hidden = :hidden,
            modified_at = :modifiedAt,
            verified = :verified,
            parameters_id = :parametersId,
            client_epoch = :clientEpoch,
            has_active_exception = :hasActiveException,
            version = :version,
            created_at = :createdAt,
            created_by = :createdBy,
            has_variations = :hasVariations,
            impacted_by = :impactedBy::jsonb,
            modified_by = :modifiedBy,
            state = :state,
            task_executions_id = :taskExecutionsId,
            choices = :choices::jsonb,
            has_exceptions = :hasExceptions,
            value = :value,
            jobs_id = :jobsId,
            parameter_value_approval_id = :parameterValueApprovalId
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM parameter_values
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM parameter_values
        WHERE id = :id
        """;

    public static final String FIND_BY_PARAMETERS_ID = """
        SELECT reason, has_corrections, hidden, modified_at, verified, parameters_id, client_epoch, has_active_exception, version, created_at, created_by, has_variations, impacted_by, modified_by, id, state, task_executions_id, choices, has_exceptions, value, jobs_id, parameter_value_approval_id
        FROM parameter_values
        WHERE parameters_id = :parametersId
        """;

    public static final String FIND_BY_TASK_EXECUTIONS_ID = """
        SELECT reason, has_corrections, hidden, modified_at, verified, parameters_id, client_epoch, has_active_exception, version, created_at, created_by, has_variations, impacted_by, modified_by, id, state, task_executions_id, choices, has_exceptions, value, jobs_id, parameter_value_approval_id
        FROM parameter_values
        WHERE task_executions_id = :taskExecutionsId
        """;

    public static final String FIND_BY_PARAMETER_VALUE_APPROVAL_ID = """
        SELECT reason, has_corrections, hidden, modified_at, verified, parameters_id, client_epoch, has_active_exception, version, created_at, created_by, has_variations, impacted_by, modified_by, id, state, task_executions_id, choices, has_exceptions, value, jobs_id, parameter_value_approval_id
        FROM parameter_values
        WHERE parameter_value_approval_id = :parameterValueApprovalId
        """;

    public static final String FIND_BY_MODIFIED_BY = """
        SELECT reason, has_corrections, hidden, modified_at, verified, parameters_id, client_epoch, has_active_exception, version, created_at, created_by, has_variations, impacted_by, modified_by, id, state, task_executions_id, choices, has_exceptions, value, jobs_id, parameter_value_approval_id
        FROM parameter_values
        WHERE modified_by = :modifiedBy
        """;

    public static final String FIND_BY_JOBS_ID = """
        SELECT reason, has_corrections, hidden, modified_at, verified, parameters_id, client_epoch, has_active_exception, version, created_at, created_by, has_variations, impacted_by, modified_by, id, state, task_executions_id, choices, has_exceptions, value, jobs_id, parameter_value_approval_id
        FROM parameter_values
        WHERE jobs_id = :jobsId
        """;

    public static final String FIND_BY_CREATED_BY = """
        SELECT reason, has_corrections, hidden, modified_at, verified, parameters_id, client_epoch, has_active_exception, version, created_at, created_by, has_variations, impacted_by, modified_by, id, state, task_executions_id, choices, has_exceptions, value, jobs_id, parameter_value_approval_id
        FROM parameter_values
        WHERE created_by = :createdBy
        """;

    private ParameterValuesSql() {
        // Utility class
    }
}
