package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for Permission entity
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public final class PermissionSql {

    public static final String FIND_ALL = """
        SELECT created_at, archived, path, method, created_by, modified_at, name, description, modified_by, id, services_id
        FROM permissions
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM permissions
        """;

    public static final String FIND_BY_ID = """
        SELECT created_at, archived, path, method, created_by, modified_at, name, description, modified_by, id, services_id
        FROM permissions
        WHERE id = :id
        """;

    public static final String INSERT = """
        INSERT INTO permissions (created_at, archived, path, method, created_by, modified_at, name, description, modified_by, services_id)
        VALUES (:createdAt, :archived, :path, :method, :createdBy, :modifiedAt, :name, :description, :modifiedBy, :servicesId)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE permissions SET
            created_at = :createdAt,
            archived = :archived,
            path = :path,
            method = :method,
            created_by = :createdBy,
            modified_at = :modifiedAt,
            name = :name,
            description = :description,
            modified_by = :modifiedBy,
            services_id = :servicesId
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM permissions
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM permissions
        WHERE id = :id
        """;

    public static final String FIND_BY_SERVICES_ID = """
        SELECT created_at, archived, path, method, created_by, modified_at, name, description, modified_by, id, services_id
        FROM permissions
        WHERE services_id = :servicesId
        """;

    public static final String FIND_BY_MODIFIED_BY = """
        SELECT created_at, archived, path, method, created_by, modified_at, name, description, modified_by, id, services_id
        FROM permissions
        WHERE modified_by = :modifiedBy
        """;

    public static final String FIND_BY_CREATED_BY = """
        SELECT created_at, archived, path, method, created_by, modified_at, name, description, modified_by, id, services_id
        FROM permissions
        WHERE created_by = :createdBy
        """;

    private PermissionSql() {
        // Utility class
    }
}
