package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for QrtzSimpleTrigger entity
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public final class QrtzSimpleTriggerSql {

    public static final String FIND_ALL = """
        SELECT trigger_group, trigger_name, repeat_interval, sched_name, times_triggered, repeat_count
        FROM qrtz_simple_triggers
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM qrtz_simple_triggers
        """;

    public static final String FIND_BY_TRIGGER_NAME_AND_SCHED_NAME_AND_TRIGGER_GROUP = """
        SELECT trigger_group, trigger_name, repeat_interval, sched_name, times_triggered, repeat_count
        FROM qrtz_simple_triggers
        WHERE trigger_name = :triggerName AND sched_name = :schedName AND trigger_group = :triggerGroup
        """;

    public static final String INSERT = """
        INSERT INTO qrtz_simple_triggers (trigger_group, trigger_name, repeat_interval, sched_name, times_triggered, repeat_count)
        VALUES (:triggerGroup, :triggerName, :repeatInterval, :schedName, :timesTriggered, :repeatCount)
        """;

    public static final String UPDATE = """
        UPDATE qrtz_simple_triggers SET
            trigger_group = :triggerGroup,
            trigger_name = :triggerName,
            repeat_interval = :repeatInterval,
            sched_name = :schedName,
            times_triggered = :timesTriggered,
            repeat_count = :repeatCount
        WHERE trigger_name = :triggerName AND sched_name = :schedName AND trigger_group = :triggerGroup
        """;

    public static final String DELETE_BY_TRIGGER_NAME_AND_SCHED_NAME_AND_TRIGGER_GROUP = """
        DELETE FROM qrtz_simple_triggers
        WHERE trigger_name = :triggerName AND sched_name = :schedName AND trigger_group = :triggerGroup
        """;

    public static final String EXISTS_BY_TRIGGER_NAME_AND_SCHED_NAME_AND_TRIGGER_GROUP = """
        SELECT COUNT(*) FROM qrtz_simple_triggers
        WHERE trigger_name = :triggerName AND sched_name = :schedName AND trigger_group = :triggerGroup
        """;

    public static final String FIND_BY_TRIGGER_NAME = """
        SELECT trigger_group, trigger_name, repeat_interval, sched_name, times_triggered, repeat_count
        FROM qrtz_simple_triggers
        WHERE trigger_name = :triggerName
        """;

    public static final String FIND_BY_SCHED_NAME = """
        SELECT trigger_group, trigger_name, repeat_interval, sched_name, times_triggered, repeat_count
        FROM qrtz_simple_triggers
        WHERE sched_name = :schedName
        """;

    public static final String FIND_BY_TRIGGER_GROUP = """
        SELECT trigger_group, trigger_name, repeat_interval, sched_name, times_triggered, repeat_count
        FROM qrtz_simple_triggers
        WHERE trigger_group = :triggerGroup
        """;

    private QrtzSimpleTriggerSql() {
        // Utility class
    }
}
