package com.example.daoGenerator.dao.sql;

/**
 * SQL constants for QrtzBlobTriggers entity
 * Generated by JDBC DAO Generator
 */
public final class QrtzBlobTriggersSql {

    public static final String FIND_BY_ID = """
        SELECT trigger_group, blob_data, trigger_name, sched_name
        FROM qrtz_blob_triggers
        WHERE id = :id
        """;

    public static final String FIND_ALL = """
        SELECT trigger_group, blob_data, trigger_name, sched_name
        FROM qrtz_blob_triggers
        """;

    public static final String INSERT = """
        INSERT INTO qrtz_blob_triggers (trigger_group, blob_data, trigger_name, sched_name)
        VALUES (:triggerGroup, :blobData, :triggerName, :schedName)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE qrtz_blob_triggers SET
            trigger_group = :triggerGroup,
            blob_data = :blobData,
            trigger_name = :triggerName,
            sched_name = :schedName
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM qrtz_blob_triggers
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM qrtz_blob_triggers
        WHERE id = :id
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM qrtz_blob_triggers
        """;

    public static final String FIND_BY_TRIGGER_NAME = """
        SELECT trigger_group, blob_data, trigger_name, sched_name
        FROM qrtz_blob_triggers
        WHERE trigger_name = :triggerName
        """;

    public static final String FIND_BY_SCHED_NAME = """
        SELECT trigger_group, blob_data, trigger_name, sched_name
        FROM qrtz_blob_triggers
        WHERE sched_name = :schedName
        """;

    public static final String FIND_BY_TRIGGER_GROUP = """
        SELECT trigger_group, blob_data, trigger_name, sched_name
        FROM qrtz_blob_triggers
        WHERE trigger_group = :triggerGroup
        """;

    private QrtzBlobTriggersSql() {
        // Utility class
    }
}
