package com.example.daoGenerator.dao.sql;

/**
 * SQL constants for QrtzLocks entity
 * Generated by JDBC DAO Generator
 */
public final class QrtzLocksSql {

    public static final String FIND_BY_ID = """
        SELECT sched_name, lock_name
        FROM qrtz_locks
        WHERE id = :id
        """;

    public static final String FIND_ALL = """
        SELECT sched_name, lock_name
        FROM qrtz_locks
        """;

    public static final String INSERT = """
        INSERT INTO qrtz_locks (sched_name, lock_name)
        VALUES (:schedName, :lockName)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE qrtz_locks SET
            sched_name = :schedName,
            lock_name = :lockName
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM qrtz_locks
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM qrtz_locks
        WHERE id = :id
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM qrtz_locks
        """;

    private QrtzLocksSql() {
        // Utility class
    }
}
