package com.example.daoGenerator.dao.sql;

/**
 * SQL constants for QrtzPausedTriggerGrps entity
 * Generated by JDBC DAO Generator
 */
public final class QrtzPausedTriggerGrpsSql {

    public static final String FIND_BY_ID = """
        SELECT trigger_group, sched_name
        FROM qrtz_paused_trigger_grps
        WHERE id = :id
        """;

    public static final String FIND_ALL = """
        SELECT trigger_group, sched_name
        FROM qrtz_paused_trigger_grps
        """;

    public static final String INSERT = """
        INSERT INTO qrtz_paused_trigger_grps (trigger_group, sched_name)
        VALUES (:triggerGroup, :schedName)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE qrtz_paused_trigger_grps SET
            trigger_group = :triggerGroup,
            sched_name = :schedName
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM qrtz_paused_trigger_grps
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM qrtz_paused_trigger_grps
        WHERE id = :id
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM qrtz_paused_trigger_grps
        """;

    private QrtzPausedTriggerGrpsSql() {
        // Utility class
    }
}
