package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for RoleScopeGroupsMapping entity
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public final class RoleScopeGroupsMappingSql {

    public static final String FIND_ALL = """
        SELECT scope_groups_id, created_at, created_by, roles_id
        FROM role_scope_groups_mapping
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM role_scope_groups_mapping
        """;

    public static final String FIND_BY_ROLES_ID_AND_SCOPE_GROUPS_ID = """
        SELECT scope_groups_id, created_at, created_by, roles_id
        FROM role_scope_groups_mapping
        WHERE roles_id = :rolesId AND scope_groups_id = :scopeGroupsId
        """;

    public static final String INSERT = """
        INSERT INTO role_scope_groups_mapping (scope_groups_id, created_at, created_by, roles_id)
        VALUES (:scopeGroupsId, :createdAt, :createdBy, :rolesId)
        """;

    public static final String UPDATE = """
        UPDATE role_scope_groups_mapping SET
            scope_groups_id = :scopeGroupsId,
            created_at = :createdAt,
            created_by = :createdBy,
            roles_id = :rolesId
        WHERE roles_id = :rolesId AND scope_groups_id = :scopeGroupsId
        """;

    public static final String DELETE_BY_ROLES_ID_AND_SCOPE_GROUPS_ID = """
        DELETE FROM role_scope_groups_mapping
        WHERE roles_id = :rolesId AND scope_groups_id = :scopeGroupsId
        """;

    public static final String EXISTS_BY_ROLES_ID_AND_SCOPE_GROUPS_ID = """
        SELECT COUNT(*) FROM role_scope_groups_mapping
        WHERE roles_id = :rolesId AND scope_groups_id = :scopeGroupsId
        """;

    public static final String FIND_BY_ROLES_ID = """
        SELECT scope_groups_id, created_at, created_by, roles_id
        FROM role_scope_groups_mapping
        WHERE roles_id = :rolesId
        """;

    public static final String FIND_BY_SCOPE_GROUPS_ID = """
        SELECT scope_groups_id, created_at, created_by, roles_id
        FROM role_scope_groups_mapping
        WHERE scope_groups_id = :scopeGroupsId
        """;

    public static final String FIND_BY_CREATED_BY = """
        SELECT scope_groups_id, created_at, created_by, roles_id
        FROM role_scope_groups_mapping
        WHERE created_by = :createdBy
        """;

    private RoleScopeGroupsMappingSql() {
        // Utility class
    }
}
