package com.example.daoGenerator.dao.sql;

/**
 * SQL constants for ScopeGroups entity
 * Generated by JDBC DAO Generator
 */
public final class ScopeGroupsSql {

    public static final String FIND_BY_ID = """
        SELECT created_at, archived, created_by, order_tree, modified_at, name, modified_by, id, services_id
        FROM scope_groups
        WHERE id = :id
        """;

    public static final String FIND_ALL = """
        SELECT created_at, archived, created_by, order_tree, modified_at, name, modified_by, id, services_id
        FROM scope_groups
        """;

    public static final String INSERT = """
        INSERT INTO scope_groups (created_at, archived, created_by, order_tree, modified_at, name, modified_by, services_id)
        VALUES (:createdAt, :archived, :createdBy, :orderTree, :modifiedAt, :name, :modifiedBy, :servicesId)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE scope_groups SET
            created_at = :createdAt,
            archived = :archived,
            created_by = :createdBy,
            order_tree = :orderTree,
            modified_at = :modifiedAt,
            name = :name,
            modified_by = :modifiedBy,
            services_id = :servicesId
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM scope_groups
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM scope_groups
        WHERE id = :id
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM scope_groups
        """;

    public static final String FIND_BY_SERVICES_ID = """
        SELECT created_at, archived, created_by, order_tree, modified_at, name, modified_by, id, services_id
        FROM scope_groups
        WHERE services_id = :servicesId
        """;

    public static final String FIND_BY_MODIFIED_BY = """
        SELECT created_at, archived, created_by, order_tree, modified_at, name, modified_by, id, services_id
        FROM scope_groups
        WHERE modified_by = :modifiedBy
        """;

    public static final String FIND_BY_CREATED_BY = """
        SELECT created_at, archived, created_by, order_tree, modified_at, name, modified_by, id, services_id
        FROM scope_groups
        WHERE created_by = :createdBy
        """;

    private ScopeGroupsSql() {
        // Utility class
    }
}
