package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for TaskSchedules entity
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public final class TaskSchedulesSql {

    public static final String FIND_ALL = """
        SELECT created_at, condition, start_date_interval, created_by, referenced_tasks_id, modified_at, due_date_duration, due_date_interval, modified_by, id, type, start_date_duration
        FROM task_schedules
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM task_schedules
        """;

    public static final String FIND_BY_ID = """
        SELECT created_at, condition, start_date_interval, created_by, referenced_tasks_id, modified_at, due_date_duration, due_date_interval, modified_by, id, type, start_date_duration
        FROM task_schedules
        WHERE id = :id
        """;

    public static final String INSERT = """
        INSERT INTO task_schedules (created_at, condition, start_date_interval, created_by, referenced_tasks_id, modified_at, due_date_duration, due_date_interval, modified_by, type, start_date_duration)
        VALUES (:createdAt, :condition, :startDateInterval, :createdBy, :referencedTasksId, :modifiedAt, :dueDateDuration::jsonb, :dueDateInterval, :modifiedBy, :type, :startDateDuration::jsonb)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE task_schedules SET
            created_at = :createdAt,
            condition = :condition,
            start_date_interval = :startDateInterval,
            created_by = :createdBy,
            referenced_tasks_id = :referencedTasksId,
            modified_at = :modifiedAt,
            due_date_duration = :dueDateDuration::jsonb,
            due_date_interval = :dueDateInterval,
            modified_by = :modifiedBy,
            type = :type,
            start_date_duration = :startDateDuration::jsonb
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM task_schedules
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM task_schedules
        WHERE id = :id
        """;

    public static final String FIND_BY_REFERENCED_TASKS_ID = """
        SELECT created_at, condition, start_date_interval, created_by, referenced_tasks_id, modified_at, due_date_duration, due_date_interval, modified_by, id, type, start_date_duration
        FROM task_schedules
        WHERE referenced_tasks_id = :referencedTasksId
        """;

    private TaskSchedulesSql() {
        // Utility class
    }
}
