package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for TaskMediaMapping entity
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public final class TaskMediaMappingSql {

    public static final String FIND_ALL = """
        SELECT created_at, medias_id, created_by, tasks_id, modified_at, modified_by
        FROM task_media_mapping
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM task_media_mapping
        """;

    public static final String FIND_BY_TASKS_ID_AND_MEDIAS_ID = """
        SELECT created_at, medias_id, created_by, tasks_id, modified_at, modified_by
        FROM task_media_mapping
        WHERE tasks_id = :tasksId AND medias_id = :mediasId
        """;

    public static final String INSERT = """
        INSERT INTO task_media_mapping (created_at, medias_id, created_by, tasks_id, modified_at, modified_by)
        VALUES (:createdAt, :mediasId, :createdBy, :tasksId, :modifiedAt, :modifiedBy)
        """;

    public static final String UPDATE = """
        UPDATE task_media_mapping SET
            created_at = :createdAt,
            medias_id = :mediasId,
            created_by = :createdBy,
            tasks_id = :tasksId,
            modified_at = :modifiedAt,
            modified_by = :modifiedBy
        WHERE tasks_id = :tasksId AND medias_id = :mediasId
        """;

    public static final String DELETE_BY_TASKS_ID_AND_MEDIAS_ID = """
        DELETE FROM task_media_mapping
        WHERE tasks_id = :tasksId AND medias_id = :mediasId
        """;

    public static final String EXISTS_BY_TASKS_ID_AND_MEDIAS_ID = """
        SELECT COUNT(*) FROM task_media_mapping
        WHERE tasks_id = :tasksId AND medias_id = :mediasId
        """;

    public static final String FIND_BY_TASKS_ID = """
        SELECT created_at, medias_id, created_by, tasks_id, modified_at, modified_by
        FROM task_media_mapping
        WHERE tasks_id = :tasksId
        """;

    public static final String FIND_BY_MODIFIED_BY = """
        SELECT created_at, medias_id, created_by, tasks_id, modified_at, modified_by
        FROM task_media_mapping
        WHERE modified_by = :modifiedBy
        """;

    public static final String FIND_BY_MEDIAS_ID = """
        SELECT created_at, medias_id, created_by, tasks_id, modified_at, modified_by
        FROM task_media_mapping
        WHERE medias_id = :mediasId
        """;

    public static final String FIND_BY_CREATED_BY = """
        SELECT created_at, medias_id, created_by, tasks_id, modified_at, modified_by
        FROM task_media_mapping
        WHERE created_by = :createdBy
        """;

    private TaskMediaMappingSql() {
        // Utility class
    }
}
