package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for TrainedUserTasksMapping entity
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public final class TrainedUserTasksMappingSql {

    public static final String FIND_ALL = """
        SELECT trained_users_id, created_at, created_by, tasks_id, modified_at, modified_by, id
        FROM trained_user_tasks_mapping
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM trained_user_tasks_mapping
        """;

    public static final String FIND_BY_ID = """
        SELECT trained_users_id, created_at, created_by, tasks_id, modified_at, modified_by, id
        FROM trained_user_tasks_mapping
        WHERE id = :id
        """;

    public static final String INSERT = """
        INSERT INTO trained_user_tasks_mapping (trained_users_id, created_at, created_by, tasks_id, modified_at, modified_by)
        VALUES (:trainedUsersId, :createdAt, :createdBy, :tasksId, :modifiedAt, :modifiedBy)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE trained_user_tasks_mapping SET
            trained_users_id = :trainedUsersId,
            created_at = :createdAt,
            created_by = :createdBy,
            tasks_id = :tasksId,
            modified_at = :modifiedAt,
            modified_by = :modifiedBy
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM trained_user_tasks_mapping
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM trained_user_tasks_mapping
        WHERE id = :id
        """;

    public static final String FIND_BY_TASKS_ID = """
        SELECT trained_users_id, created_at, created_by, tasks_id, modified_at, modified_by, id
        FROM trained_user_tasks_mapping
        WHERE tasks_id = :tasksId
        """;

    public static final String FIND_BY_TRAINED_USERS_ID = """
        SELECT trained_users_id, created_at, created_by, tasks_id, modified_at, modified_by, id
        FROM trained_user_tasks_mapping
        WHERE trained_users_id = :trainedUsersId
        """;

    private TrainedUserTasksMappingSql() {
        // Utility class
    }
}
