package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for UserAudit entity
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public final class UserAuditSql {

    public static final String FIND_ALL = """
        SELECT severity, organisations_id, action, details, id, triggered_at, facility_ids, triggered_by
        FROM user_audits
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM user_audits
        """;

    public static final String FIND_BY_ID = """
        SELECT severity, organisations_id, action, details, id, triggered_at, facility_ids, triggered_by
        FROM user_audits
        WHERE id = :id
        """;

    public static final String INSERT = """
        INSERT INTO user_audits (severity, organisations_id, action, details, triggered_at, facility_ids, triggered_by)
        VALUES (:severity, :organisationsId, :action, :details, :triggeredAt, :facilityIds, :triggeredBy)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE user_audits SET
            severity = :severity,
            organisations_id = :organisationsId,
            action = :action,
            details = :details,
            triggered_at = :triggeredAt,
            facility_ids = :facilityIds,
            triggered_by = :triggeredBy
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM user_audits
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM user_audits
        WHERE id = :id
        """;

    private UserAuditSql() {
        // Utility class
    }
}
