package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for Users entity
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public final class UsersSql {

    public static final String FIND_ALL = """
        SELECT last_name, organisations_id, failed_additional_verification_attempts, modified_at, failed_challenge_question_attempts, locked_at, employee_id, failed_login_attempts, type, created_at, first_name, archived, password_updated_at, challenge_questions_answer, password, challenge_questions_id, created_by, is_system_user, modified_by, id, state, department, email, username
        FROM users
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM users
        """;

    public static final String FIND_BY_ID = """
        SELECT last_name, organisations_id, failed_additional_verification_attempts, modified_at, failed_challenge_question_attempts, locked_at, employee_id, failed_login_attempts, type, created_at, first_name, archived, password_updated_at, challenge_questions_answer, password, challenge_questions_id, created_by, is_system_user, modified_by, id, state, department, email, username
        FROM users
        WHERE id = :id
        """;

    public static final String INSERT = """
        INSERT INTO users (last_name, organisations_id, failed_additional_verification_attempts, modified_at, failed_challenge_question_attempts, locked_at, employee_id, failed_login_attempts, type, created_at, first_name, archived, password_updated_at, challenge_questions_answer, password, challenge_questions_id, created_by, is_system_user, modified_by, state, department, email, username)
        VALUES (:lastName, :organisationsId, :failedAdditionalVerificationAttempts, :modifiedAt, :failedChallengeQuestionAttempts, :lockedAt, :employeeId, :failedLoginAttempts, :type, :createdAt, :firstName, :archived, :passwordUpdatedAt, :challengeQuestionsAnswer, :password, :challengeQuestionsId, :createdBy, :isSystemUser, :modifiedBy, :state, :department, :email, :username)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE users SET
            last_name = :lastName,
            organisations_id = :organisationsId,
            failed_additional_verification_attempts = :failedAdditionalVerificationAttempts,
            modified_at = :modifiedAt,
            failed_challenge_question_attempts = :failedChallengeQuestionAttempts,
            locked_at = :lockedAt,
            employee_id = :employeeId,
            failed_login_attempts = :failedLoginAttempts,
            type = :type,
            created_at = :createdAt,
            first_name = :firstName,
            archived = :archived,
            password_updated_at = :passwordUpdatedAt,
            challenge_questions_answer = :challengeQuestionsAnswer,
            password = :password,
            challenge_questions_id = :challengeQuestionsId,
            created_by = :createdBy,
            is_system_user = :isSystemUser,
            modified_by = :modifiedBy,
            state = :state,
            department = :department,
            email = :email,
            username = :username
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM users
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM users
        WHERE id = :id
        """;

    public static final String FIND_BY_CHALLENGE_QUESTIONS_ID = """
        SELECT last_name, organisations_id, failed_additional_verification_attempts, modified_at, failed_challenge_question_attempts, locked_at, employee_id, failed_login_attempts, type, created_at, first_name, archived, password_updated_at, challenge_questions_answer, password, challenge_questions_id, created_by, is_system_user, modified_by, id, state, department, email, username
        FROM users
        WHERE challenge_questions_id = :challengeQuestionsId
        """;

    public static final String FIND_BY_MODIFIED_BY = """
        SELECT last_name, organisations_id, failed_additional_verification_attempts, modified_at, failed_challenge_question_attempts, locked_at, employee_id, failed_login_attempts, type, created_at, first_name, archived, password_updated_at, challenge_questions_answer, password, challenge_questions_id, created_by, is_system_user, modified_by, id, state, department, email, username
        FROM users
        WHERE modified_by = :modifiedBy
        """;

    public static final String FIND_BY_ORGANISATIONS_ID = """
        SELECT last_name, organisations_id, failed_additional_verification_attempts, modified_at, failed_challenge_question_attempts, locked_at, employee_id, failed_login_attempts, type, created_at, first_name, archived, password_updated_at, challenge_questions_answer, password, challenge_questions_id, created_by, is_system_user, modified_by, id, state, department, email, username
        FROM users
        WHERE organisations_id = :organisationsId
        """;

    public static final String FIND_BY_CREATED_BY = """
        SELECT last_name, organisations_id, failed_additional_verification_attempts, modified_at, failed_challenge_question_attempts, locked_at, employee_id, failed_login_attempts, type, created_at, first_name, archived, password_updated_at, challenge_questions_answer, password, challenge_questions_id, created_by, is_system_user, modified_by, id, state, department, email, username
        FROM users
        WHERE created_by = :createdBy
        """;

    private UsersSql() {
        // Utility class
    }
}
