package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for UserRolesMapping entity
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public final class UserRolesMappingSql {

    public static final String FIND_ALL = """
        SELECT created_at, created_by, users_id, roles_id
        FROM user_roles_mapping
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM user_roles_mapping
        """;

    public static final String FIND_BY_ROLES_ID_AND_USERS_ID = """
        SELECT created_at, created_by, users_id, roles_id
        FROM user_roles_mapping
        WHERE roles_id = :rolesId AND users_id = :usersId
        """;

    public static final String INSERT = """
        INSERT INTO user_roles_mapping (created_at, created_by, users_id, roles_id)
        VALUES (:createdAt, :createdBy, :usersId, :rolesId)
        """;

    public static final String UPDATE = """
        UPDATE user_roles_mapping SET
            created_at = :createdAt,
            created_by = :createdBy,
            users_id = :usersId,
            roles_id = :rolesId
        WHERE roles_id = :rolesId AND users_id = :usersId
        """;

    public static final String DELETE_BY_ROLES_ID_AND_USERS_ID = """
        DELETE FROM user_roles_mapping
        WHERE roles_id = :rolesId AND users_id = :usersId
        """;

    public static final String EXISTS_BY_ROLES_ID_AND_USERS_ID = """
        SELECT COUNT(*) FROM user_roles_mapping
        WHERE roles_id = :rolesId AND users_id = :usersId
        """;

    public static final String FIND_BY_ROLES_ID = """
        SELECT created_at, created_by, users_id, roles_id
        FROM user_roles_mapping
        WHERE roles_id = :rolesId
        """;

    public static final String FIND_BY_USERS_ID = """
        SELECT created_at, created_by, users_id, roles_id
        FROM user_roles_mapping
        WHERE users_id = :usersId
        """;

    public static final String FIND_BY_CREATED_BY = """
        SELECT created_at, created_by, users_id, roles_id
        FROM user_roles_mapping
        WHERE created_by = :createdBy
        """;

    private UserRolesMappingSql() {
        // Utility class
    }
}
