package com.example.daoGenerator.dao.sql;

/**
 * Enhanced SQL constants for Variation entity
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public final class VariationSql {

    public static final String FIND_ALL = """
        SELECT old_details, modified_at, description, new_details, type, variation_number, parameter_values_id, created_at, created_by, config_id, name, modified_by, id, jobs_id
        FROM variations
        """;

    public static final String COUNT = """
        SELECT COUNT(*) FROM variations
        """;

    public static final String FIND_BY_ID = """
        SELECT old_details, modified_at, description, new_details, type, variation_number, parameter_values_id, created_at, created_by, config_id, name, modified_by, id, jobs_id
        FROM variations
        WHERE id = :id
        """;

    public static final String INSERT = """
        INSERT INTO variations (old_details, modified_at, description, new_details, type, variation_number, parameter_values_id, created_at, created_by, config_id, name, modified_by, jobs_id)
        VALUES (:oldDetails::jsonb, :modifiedAt, :description, :newDetails::jsonb, :type, :variationNumber, :parameterValuesId, :createdAt, :createdBy, :configId, :name, :modifiedBy, :jobsId)
        RETURNING id
        """;

    public static final String UPDATE = """
        UPDATE variations SET
            old_details = :oldDetails::jsonb,
            modified_at = :modifiedAt,
            description = :description,
            new_details = :newDetails::jsonb,
            type = :type,
            variation_number = :variationNumber,
            parameter_values_id = :parameterValuesId,
            created_at = :createdAt,
            created_by = :createdBy,
            config_id = :configId,
            name = :name,
            modified_by = :modifiedBy,
            jobs_id = :jobsId
        WHERE id = :id
        """;

    public static final String DELETE_BY_ID = """
        DELETE FROM variations
        WHERE id = :id
        """;

    public static final String EXISTS_BY_ID = """
        SELECT COUNT(*) FROM variations
        WHERE id = :id
        """;

    public static final String FIND_BY_PARAMETER_VALUES_ID = """
        SELECT old_details, modified_at, description, new_details, type, variation_number, parameter_values_id, created_at, created_by, config_id, name, modified_by, id, jobs_id
        FROM variations
        WHERE parameter_values_id = :parameterValuesId
        """;

    public static final String FIND_BY_JOBS_ID = """
        SELECT old_details, modified_at, description, new_details, type, variation_number, parameter_values_id, created_at, created_by, config_id, name, modified_by, id, jobs_id
        FROM variations
        WHERE jobs_id = :jobsId
        """;

    private VariationSql() {
        // Utility class
    }
}
