package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.AutoInitializedParameter;

/**
 * Enhanced DAO interface for AutoInitializedParameter entity
 * Table: auto_initialized_parameters
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface AutoInitializedParameterDao {

    // Single ID operations
    Optional<AutoInitializedParameter> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<AutoInitializedParameter> findAll();
    AutoInitializedParameter save(AutoInitializedParameter entity);
    long count();

    // Foreign key based finders
    List<AutoInitializedParameter> findByReferencedParametersId(Long referencedParametersId);
    List<AutoInitializedParameter> findByChecklistsId(Long checklistsId);
    List<AutoInitializedParameter> findByAutoInitializedParametersId(Long autoInitializedParametersId);

}
