package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.Checklist;

/**
 * Enhanced DAO interface for Checklist entity
 * Table: checklists
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface ChecklistDao {

    // Single ID operations
    Optional<Checklist> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<Checklist> findAll();
    Checklist save(Checklist entity);
    long count();

    // Foreign key based finders
    List<Checklist> findByUseCasesId(Long useCasesId);
    List<Checklist> findByReleasedBy(Long releasedBy);
    List<Checklist> findByModifiedBy(Long modifiedBy);
    List<Checklist> findByOrganisationsId(Long organisationsId);
    List<Checklist> findByCreatedBy(Long createdBy);
    List<Checklist> findByVersionsId(Long versionsId);

}
