package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.ChecklistPropertyValue;

/**
 * Enhanced DAO interface for ChecklistPropertyValue entity
 * Table: checklist_property_values
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public interface ChecklistPropertyValueDao {

    // Composite key operations
    Optional<ChecklistPropertyValue> findByFacilityUseCasePropertyMappingIdAndChecklistsId(Long facilityUseCasePropertyMappingId, Long checklistsId);
    void deleteByFacilityUseCasePropertyMappingIdAndChecklistsId(Long facilityUseCasePropertyMappingId, Long checklistsId);
    boolean existsByFacilityUseCasePropertyMappingIdAndChecklistsId(Long facilityUseCasePropertyMappingId, Long checklistsId);

    // Common operations
    List<ChecklistPropertyValue> findAll();
    ChecklistPropertyValue save(ChecklistPropertyValue entity);
    long count();

    // Foreign key based finders
    List<ChecklistPropertyValue> findByChecklistsId(Long checklistsId);
    List<ChecklistPropertyValue> findByFacilityUseCasePropertyMappingId(Long facilityUseCasePropertyMappingId);
    List<ChecklistPropertyValue> findByModifiedBy(Long modifiedBy);
    List<ChecklistPropertyValue> findByCreatedBy(Long createdBy);

}
