package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.ChecklistPropertyValues;

/**
 * Enhanced DAO interface for ChecklistPropertyValues entity
 * Table: checklist_property_values
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public interface ChecklistPropertyValuesDao {

    // Composite key operations
    Optional<ChecklistPropertyValues> findByFacilityUseCasePropertyMappingIdAndChecklistsId(Long facilityUseCasePropertyMappingId, Long checklistsId);
    void deleteByFacilityUseCasePropertyMappingIdAndChecklistsId(Long facilityUseCasePropertyMappingId, Long checklistsId);
    boolean existsByFacilityUseCasePropertyMappingIdAndChecklistsId(Long facilityUseCasePropertyMappingId, Long checklistsId);

    // Common operations
    List<ChecklistPropertyValues> findAll();
    ChecklistPropertyValues save(ChecklistPropertyValues entity);
    long count();

    // Foreign key based finders
    List<ChecklistPropertyValues> findByChecklistsId(Long checklistsId);
    List<ChecklistPropertyValues> findByFacilityUseCasePropertyMappingId(Long facilityUseCasePropertyMappingId);
    List<ChecklistPropertyValues> findByModifiedBy(Long modifiedBy);
    List<ChecklistPropertyValues> findByCreatedBy(Long createdBy);

}
