package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.ClientFacilityMapping;

/**
 * Enhanced DAO interface for ClientFacilityMapping entity
 * Table: client_facility_mapping
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public interface ClientFacilityMappingDao {

    // Composite key operations
    Optional<ClientFacilityMapping> findByFacilitiesIdAndClientId(Long facilitiesId, String clientId);
    void deleteByFacilitiesIdAndClientId(Long facilitiesId, String clientId);
    boolean existsByFacilitiesIdAndClientId(Long facilitiesId, String clientId);

    // Common operations
    List<ClientFacilityMapping> findAll();
    ClientFacilityMapping save(ClientFacilityMapping entity);
    long count();

    // Foreign key based finders
    List<ClientFacilityMapping> findByModifiedBy(Long modifiedBy);
    List<ClientFacilityMapping> findByFacilitiesId(Long facilitiesId);
    List<ClientFacilityMapping> findByCreatedBy(Long createdBy);
    List<ClientFacilityMapping> findByClientId(Long clientId);

}
