package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.Exceptions;

/**
 * DAO interface for Exceptions entity
 * Table: exceptions
 * Generated by JDBC DAO Generator
 */
public interface ExceptionsDao {

    // Basic CRUD operations
    Optional<Exceptions> findById(Long id);
    List<Exceptions> findAll();
    Exceptions save(Exceptions entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<Exceptions> findByTaskExecutionsId(Long taskExecutionsId);
    List<Exceptions> findByParameterValuesId(Long parameterValuesId);
    List<Exceptions> findByFacilitiesId(Long facilitiesId);
    List<Exceptions> findByJobsId(Long jobsId);

}
