package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.Facilities;

/**
 * Enhanced DAO interface for Facilities entity
 * Table: facilities
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface FacilitiesDao {

    // Single ID operations
    Optional<Facilities> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<Facilities> findAll();
    Facilities save(Facilities entity);
    long count();

    // Foreign key based finders
    List<Facilities> findByModifiedBy(Long modifiedBy);
    List<Facilities> findByOrganisationsId(Long organisationsId);
    List<Facilities> findByCreatedBy(Long createdBy);

}
