package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.JobAnnotations;

/**
 * Enhanced DAO interface for JobAnnotations entity
 * Table: job_annotations
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface JobAnnotationsDao {

    // Single ID operations
    Optional<JobAnnotations> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<JobAnnotations> findAll();
    JobAnnotations save(JobAnnotations entity);
    long count();

}
