package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.JobPropertyValues;

/**
 * DAO interface for JobPropertyValues entity
 * Table: job_property_values
 * Generated by JDBC DAO Generator
 */
public interface JobPropertyValuesDao {

    // Basic CRUD operations
    Optional<JobPropertyValues> findById(Long id);
    List<JobPropertyValues> findAll();
    JobPropertyValues save(JobPropertyValues entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<JobPropertyValues> findByFacilityUseCasePropertyMappingId(Long facilityUseCasePropertyMappingId);
    List<JobPropertyValues> findByModifiedBy(Long modifiedBy);
    List<JobPropertyValues> findByJobsId(Long jobsId);
    List<JobPropertyValues> findByCreatedBy(Long createdBy);

}
