package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.Medias;

/**
 * DAO interface for Medias entity
 * Table: medias
 * Generated by JDBC DAO Generator
 */
public interface MediasDao {

    // Basic CRUD operations
    Optional<Medias> findById(Long id);
    List<Medias> findAll();
    Medias save(Medias entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<Medias> findByModifiedBy(Long modifiedBy);
    List<Medias> findByOrganisationsId(Long organisationsId);
    List<Medias> findByCreatedBy(Long createdBy);

}
