package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.OrganisationFacilitiesMapping;

/**
 * DAO interface for OrganisationFacilitiesMapping entity
 * Table: organisation_facilities_mapping
 * Generated by JDBC DAO Generator
 */
public interface OrganisationFacilitiesMappingDao {

    // Basic CRUD operations
    Optional<OrganisationFacilitiesMapping> findById(Long id);
    List<OrganisationFacilitiesMapping> findAll();
    OrganisationFacilitiesMapping save(OrganisationFacilitiesMapping entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<OrganisationFacilitiesMapping> findByOrganisationsId(Long organisationsId);
    List<OrganisationFacilitiesMapping> findByFacilitiesId(Long facilitiesId);
    List<OrganisationFacilitiesMapping> findByCreatedBy(Long createdBy);

}
