package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.ParameterValue;

/**
 * Enhanced DAO interface for ParameterValue entity
 * Table: parameter_values
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface ParameterValueDao {

    // Single ID operations
    Optional<ParameterValue> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<ParameterValue> findAll();
    ParameterValue save(ParameterValue entity);
    long count();

    // Foreign key based finders
    List<ParameterValue> findByParametersId(Long parametersId);
    List<ParameterValue> findByTaskExecutionsId(Long taskExecutionsId);
    List<ParameterValue> findByParameterValueApprovalId(Long parameterValueApprovalId);
    List<ParameterValue> findByModifiedBy(Long modifiedBy);
    List<ParameterValue> findByJobsId(Long jobsId);
    List<ParameterValue> findByCreatedBy(Long createdBy);

}
