package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.ParameterRuleMapping;

/**
 * DAO interface for ParameterRuleMapping entity
 * Table: parameter_rule_mapping
 * Generated by JDBC DAO Generator
 */
public interface ParameterRuleMappingDao {

    // Basic CRUD operations
    Optional<ParameterRuleMapping> findById(Long id);
    List<ParameterRuleMapping> findAll();
    ParameterRuleMapping save(ParameterRuleMapping entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<ParameterRuleMapping> findByTriggeringParametersId(Long triggeringParametersId);
    List<ParameterRuleMapping> findByParameterRulesId(Long parameterRulesId);
    List<ParameterRuleMapping> findByImpactedParametersId(Long impactedParametersId);

}
