package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.ParameterRule;

/**
 * Enhanced DAO interface for ParameterRule entity
 * Table: parameter_rules
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface ParameterRuleDao {

    // Single ID operations
    Optional<ParameterRule> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<ParameterRule> findAll();
    ParameterRule save(ParameterRule entity);
    long count();

}
