package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.QrtzLock;

/**
 * Enhanced DAO interface for QrtzLock entity
 * Table: qrtz_locks
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public interface QrtzLockDao {

    // Composite key operations
    Optional<QrtzLock> findByLockNameAndSchedName(String lockName, String schedName);
    void deleteByLockNameAndSchedName(String lockName, String schedName);
    boolean existsByLockNameAndSchedName(String lockName, String schedName);

    // Common operations
    List<QrtzLock> findAll();
    QrtzLock save(QrtzLock entity);
    long count();

}
