package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.QrtzJobDetails;

/**
 * DAO interface for QrtzJobDetails entity
 * Table: qrtz_job_details
 * Generated by JDBC DAO Generator
 */
public interface QrtzJobDetailsDao {

    // Basic CRUD operations
    Optional<QrtzJobDetails> findById(Long id);
    List<QrtzJobDetails> findAll();
    QrtzJobDetails save(QrtzJobDetails entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

}
