package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.QrtzBlobTrigger;

/**
 * Enhanced DAO interface for QrtzBlobTrigger entity
 * Table: qrtz_blob_triggers
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public interface QrtzBlobTriggerDao {

    // Composite key operations
    Optional<QrtzBlobTrigger> findByTriggerNameAndSchedNameAndTriggerGroup(String triggerName, String schedName, String triggerGroup);
    void deleteByTriggerNameAndSchedNameAndTriggerGroup(String triggerName, String schedName, String triggerGroup);
    boolean existsByTriggerNameAndSchedNameAndTriggerGroup(String triggerName, String schedName, String triggerGroup);

    // Common operations
    List<QrtzBlobTrigger> findAll();
    QrtzBlobTrigger save(QrtzBlobTrigger entity);
    long count();

    // Foreign key based finders
    List<QrtzBlobTrigger> findByTriggerName(Long triggerName);
    List<QrtzBlobTrigger> findBySchedName(Long schedName);
    List<QrtzBlobTrigger> findByTriggerGroup(Long triggerGroup);

}
