package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.QrtzSchedulerState;

/**
 * Enhanced DAO interface for QrtzSchedulerState entity
 * Table: qrtz_scheduler_state
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public interface QrtzSchedulerStateDao {

    // Composite key operations
    Optional<QrtzSchedulerState> findByInstanceNameAndSchedName(String instanceName, String schedName);
    void deleteByInstanceNameAndSchedName(String instanceName, String schedName);
    boolean existsByInstanceNameAndSchedName(String instanceName, String schedName);

    // Common operations
    List<QrtzSchedulerState> findAll();
    QrtzSchedulerState save(QrtzSchedulerState entity);
    long count();

}
