package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.QrtzLocks;

/**
 * DAO interface for QrtzLocks entity
 * Table: qrtz_locks
 * Generated by JDBC DAO Generator
 */
public interface QrtzLocksDao {

    // Basic CRUD operations
    Optional<QrtzLocks> findById(Long id);
    List<QrtzLocks> findAll();
    QrtzLocks save(QrtzLocks entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

}
