package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.QrtzCalendars;

/**
 * Enhanced DAO interface for QrtzCalendars entity
 * Table: qrtz_calendars
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
public interface QrtzCalendarsDao {

    // Composite key operations
    Optional<QrtzCalendars> findBySchedNameAndCalendarName(String schedName, String calendarName);
    void deleteBySchedNameAndCalendarName(String schedName, String calendarName);
    boolean existsBySchedNameAndCalendarName(String schedName, String calendarName);

    // Common operations
    List<QrtzCalendars> findAll();
    QrtzCalendars save(QrtzCalendars entity);
    long count();

}
