package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.QrtzCronTriggers;

/**
 * DAO interface for QrtzCronTriggers entity
 * Table: qrtz_cron_triggers
 * Generated by JDBC DAO Generator
 */
public interface QrtzCronTriggersDao {

    // Basic CRUD operations
    Optional<QrtzCronTriggers> findById(Long id);
    List<QrtzCronTriggers> findAll();
    QrtzCronTriggers save(QrtzCronTriggers entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<QrtzCronTriggers> findByTriggerName(Long triggerName);
    List<QrtzCronTriggers> findBySchedName(Long schedName);
    List<QrtzCronTriggers> findByTriggerGroup(Long triggerGroup);

}
