package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.RelationValues;

/**
 * DAO interface for RelationValues entity
 * Table: relation_values
 * Generated by JDBC DAO Generator
 */
public interface RelationValuesDao {

    // Basic CRUD operations
    Optional<RelationValues> findById(Long id);
    List<RelationValues> findAll();
    RelationValues save(RelationValues entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<RelationValues> findByRelationsId(Long relationsId);
    List<RelationValues> findByJobsId(Long jobsId);

}
