package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.Schedulers;

/**
 * Enhanced DAO interface for Schedulers entity
 * Table: schedulers
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface SchedulersDao {

    // Single ID operations
    Optional<Schedulers> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<Schedulers> findAll();
    Schedulers save(Schedulers entity);
    long count();

    // Foreign key based finders
    List<Schedulers> findByUseCasesId(Long useCasesId);
    List<Schedulers> findByChecklistsId(Long checklistsId);
    List<Schedulers> findByFacilitiesId(Long facilitiesId);
    List<Schedulers> findByVersionsId(Long versionsId);

}
