package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.Services;

/**
 * DAO interface for Services entity
 * Table: services
 * Generated by JDBC DAO Generator
 */
public interface ServicesDao {

    // Basic CRUD operations
    Optional<Services> findById(Long id);
    List<Services> findAll();
    Services save(Services entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<Services> findByModifiedBy(Long modifiedBy);
    List<Services> findByCreatedBy(Long createdBy);

}
