package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.TaskExecutorLock;

/**
 * Enhanced DAO interface for TaskExecutorLock entity
 * Table: task_executor_locks
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface TaskExecutorLockDao {

    // Single ID operations
    Optional<TaskExecutorLock> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<TaskExecutorLock> findAll();
    TaskExecutorLock save(TaskExecutorLock entity);
    long count();

    // Foreign key based finders
    List<TaskExecutorLock> findByTasksId(Long tasksId);
    List<TaskExecutorLock> findByModifiedBy(Long modifiedBy);
    List<TaskExecutorLock> findByReferencedTasksId(Long referencedTasksId);
    List<TaskExecutorLock> findByCreatedBy(Long createdBy);

}
