package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.TaskExecutionTimers;

/**
 * Enhanced DAO interface for TaskExecutionTimers entity
 * Table: task_execution_timers
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface TaskExecutionTimersDao {

    // Single ID operations
    Optional<TaskExecutionTimers> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<TaskExecutionTimers> findAll();
    TaskExecutionTimers save(TaskExecutionTimers entity);
    long count();

    // Foreign key based finders
    List<TaskExecutionTimers> findByTaskExecutionsId(Long taskExecutionsId);
    List<TaskExecutionTimers> findByModifiedBy(Long modifiedBy);
    List<TaskExecutionTimers> findByCreatedBy(Long createdBy);

}
