package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.TaskExecutorLocks;

/**
 * Enhanced DAO interface for TaskExecutorLocks entity
 * Table: task_executor_locks
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface TaskExecutorLocksDao {

    // Single ID operations
    Optional<TaskExecutorLocks> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<TaskExecutorLocks> findAll();
    TaskExecutorLocks save(TaskExecutorLocks entity);
    long count();

    // Foreign key based finders
    List<TaskExecutorLocks> findByTasksId(Long tasksId);
    List<TaskExecutorLocks> findByModifiedBy(Long modifiedBy);
    List<TaskExecutorLocks> findByReferencedTasksId(Long referencedTasksId);
    List<TaskExecutorLocks> findByCreatedBy(Long createdBy);

}
