package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.Users;

/**
 * DAO interface for Users entity
 * Table: users
 * Generated by JDBC DAO Generator
 */
public interface UsersDao {

    // Basic CRUD operations
    Optional<Users> findById(Long id);
    List<Users> findAll();
    Users save(Users entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<Users> findByChallengeQuestionsId(Long challengeQuestionsId);
    List<Users> findByModifiedBy(Long modifiedBy);
    List<Users> findByOrganisationsId(Long organisationsId);
    List<Users> findByCreatedBy(Long createdBy);

}
