package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.UserFacilitiesMapping;

/**
 * DAO interface for UserFacilitiesMapping entity
 * Table: user_facilities_mapping
 * Generated by JDBC DAO Generator
 */
public interface UserFacilitiesMappingDao {

    // Basic CRUD operations
    Optional<UserFacilitiesMapping> findById(Long id);
    List<UserFacilitiesMapping> findAll();
    UserFacilitiesMapping save(UserFacilitiesMapping entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<UserFacilitiesMapping> findByUsersId(Long usersId);
    List<UserFacilitiesMapping> findByFacilitiesId(Long facilitiesId);
    List<UserFacilitiesMapping> findByCreatedBy(Long createdBy);

}
