package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.UserGroupMembers;

/**
 * DAO interface for UserGroupMembers entity
 * Table: user_group_members
 * Generated by JDBC DAO Generator
 */
public interface UserGroupMembersDao {

    // Basic CRUD operations
    Optional<UserGroupMembers> findById(Long id);
    List<UserGroupMembers> findAll();
    UserGroupMembers save(UserGroupMembers entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<UserGroupMembers> findByModifiedBy(Long modifiedBy);
    List<UserGroupMembers> findByUsersId(Long usersId);
    List<UserGroupMembers> findByCreatedBy(Long createdBy);
    List<UserGroupMembers> findByGroupsId(Long groupsId);

}
