package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.UserGroups;

/**
 * Enhanced DAO interface for UserGroups entity
 * Table: user_groups
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface UserGroupsDao {

    // Single ID operations
    Optional<UserGroups> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<UserGroups> findAll();
    UserGroups save(UserGroups entity);
    long count();

    // Foreign key based finders
    List<UserGroups> findByModifiedBy(Long modifiedBy);
    List<UserGroups> findByFacilityId(Long facilityId);
    List<UserGroups> findByCreatedBy(Long createdBy);

}
