package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.UserGroupAudits;

/**
 * DAO interface for UserGroupAudits entity
 * Table: user_group_audits
 * Generated by JDBC DAO Generator
 */
public interface UserGroupAuditsDao {

    // Basic CRUD operations
    Optional<UserGroupAudits> findById(Long id);
    List<UserGroupAudits> findAll();
    UserGroupAudits save(UserGroupAudits entity);
    void deleteById(Long id);
    boolean existsById(Long id);
    long count();

    // Foreign key based finders
    List<UserGroupAudits> findByUserGroupsId(Long userGroupsId);
    List<UserGroupAudits> findByOrganisationsId(Long organisationsId);
    List<UserGroupAudits> findByFacilitiesId(Long facilitiesId);
    List<UserGroupAudits> findByTriggeredBy(Long triggeredBy);

}
