package com.example.daoGenerator.dao.interfaces;

import java.util.List;
import java.util.Optional;
import com.example.pojogenerator.pojos.Variation;

/**
 * Enhanced DAO interface for Variation entity
 * Table: variations
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
public interface VariationDao {

    // Single ID operations
    Optional<Variation> findById(Long id);
    void deleteById(Long id);
    boolean existsById(Long id);

    // Common operations
    List<Variation> findAll();
    Variation save(Variation entity);
    long count();

    // Foreign key based finders
    List<Variation> findByParameterValuesId(Long parameterValuesId);
    List<Variation> findByJobsId(Long jobsId);

}
