package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.CorrectionDao;
import com.example.pojogenerator.pojos.Correction;
import com.example.daoGenerator.dao.mapper.CorrectionRowMapper;
import com.example.daoGenerator.dao.sql.CorrectionSql;

/**
 * Enhanced JDBC implementation of CorrectionDao
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
@Repository
public class JdbcCorrectionDao implements CorrectionDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final CorrectionRowMapper rowMapper;

    public JdbcCorrectionDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new CorrectionRowMapper();
    }

    @Override
    public Optional<Correction> findById(Long id) {
        try {
            Correction result = jdbcTemplate.queryForObject(
                CorrectionSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(CorrectionSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            CorrectionSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public List<Correction> findAll() {
        return jdbcTemplate.query(CorrectionSql.FIND_ALL, rowMapper);
    }

    @Override
    public Correction save(Correction entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private Correction insert(Correction entity) {
        // Set audit fields if they exist
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            CorrectionSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private Correction update(Correction entity) {
        entity.setModifiedAt(System.currentTimeMillis());

        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(CorrectionSql.UPDATE, params);
        
        if (rowsAffected == 0) {
            throw new RuntimeException("Entity not found for update");
        }
        return entity;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(CorrectionSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<Correction> findByTaskExecutionsId(Long taskExecutionsId) {
        return jdbcTemplate.query(
            CorrectionSql.FIND_BY_TASK_EXECUTIONS_ID,
            Map.of("taskExecutionsId", taskExecutionsId),
            rowMapper
        );
    }

    @Override
    public List<Correction> findByParameterValuesId(Long parameterValuesId) {
        return jdbcTemplate.query(
            CorrectionSql.FIND_BY_PARAMETER_VALUES_ID,
            Map.of("parameterValuesId", parameterValuesId),
            rowMapper
        );
    }

    @Override
    public List<Correction> findByFacilitiesId(Long facilitiesId) {
        return jdbcTemplate.query(
            CorrectionSql.FIND_BY_FACILITIES_ID,
            Map.of("facilitiesId", facilitiesId),
            rowMapper
        );
    }

    @Override
    public List<Correction> findByJobsId(Long jobsId) {
        return jdbcTemplate.query(
            CorrectionSql.FIND_BY_JOBS_ID,
            Map.of("jobsId", jobsId),
            rowMapper
        );
    }

    private MapSqlParameterSource createParameterMap(Correction entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("reviewersReason", entity.getReviewersReason());
        params.addValue("newValue", entity.getNewValue());
        params.addValue("facilitiesId", entity.getFacilitiesId());
        params.addValue("code", entity.getCode());
        params.addValue("modifiedAt", entity.getModifiedAt());
        params.addValue("correctorsReason", entity.getCorrectorsReason());
        params.addValue("initiatorsReason", entity.getInitiatorsReason());
        params.addValue("previousState", entity.getPreviousState());
        params.addValue("parameterValuesId", entity.getParameterValuesId());
        params.addValue("createdAt", entity.getCreatedAt());
        if (entity.getNewChoices() != null) {
            params.addValue("newChoices", entity.getNewChoices().toString());
        } else {
            params.addValue("newChoices", null);
        }
        params.addValue("createdBy", entity.getCreatedBy());
        if (entity.getOldChoices() != null) {
            params.addValue("oldChoices", entity.getOldChoices().toString());
        } else {
            params.addValue("oldChoices", null);
        }
        params.addValue("modifiedBy", entity.getModifiedBy());
        params.addValue("id", entity.getId());
        params.addValue("oldValue", entity.getOldValue());
        params.addValue("taskExecutionsId", entity.getTaskExecutionsId());
        params.addValue("jobsId", entity.getJobsId());
        params.addValue("status", entity.getStatus());

        return params;
    }

}
