package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.QrtzSimpropTriggerDao;
import com.example.pojogenerator.pojos.QrtzSimpropTrigger;
import com.example.daoGenerator.dao.mapper.QrtzSimpropTriggerRowMapper;
import com.example.daoGenerator.dao.sql.QrtzSimpropTriggerSql;

/**
 * Enhanced JDBC implementation of QrtzSimpropTriggerDao
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
@Repository
public class JdbcQrtzSimpropTriggerDao implements QrtzSimpropTriggerDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final QrtzSimpropTriggerRowMapper rowMapper;

    public JdbcQrtzSimpropTriggerDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new QrtzSimpropTriggerRowMapper();
    }

    @Override
    public Optional<QrtzSimpropTrigger> findByTriggerNameAndSchedNameAndTriggerGroup(String triggerName, String schedName, String triggerGroup) {
        try {
            QrtzSimpropTrigger result = jdbcTemplate.queryForObject(
                QrtzSimpropTriggerSql.FIND_BY_TRIGGER_NAME_AND_SCHED_NAME_AND_TRIGGER_GROUP,
                Map.of("triggerName", triggerName, "schedName", schedName, "triggerGroup", triggerGroup),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public void deleteByTriggerNameAndSchedNameAndTriggerGroup(String triggerName, String schedName, String triggerGroup) {
        jdbcTemplate.update(QrtzSimpropTriggerSql.DELETE_BY_TRIGGER_NAME_AND_SCHED_NAME_AND_TRIGGER_GROUP, Map.of("triggerName", triggerName, "schedName", schedName, "triggerGroup", triggerGroup));
    }

    @Override
    public boolean existsByTriggerNameAndSchedNameAndTriggerGroup(String triggerName, String schedName, String triggerGroup) {
        Integer count = jdbcTemplate.queryForObject(
            QrtzSimpropTriggerSql.EXISTS_BY_TRIGGER_NAME_AND_SCHED_NAME_AND_TRIGGER_GROUP,
            Map.of("triggerName", triggerName, "schedName", schedName, "triggerGroup", triggerGroup),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public List<QrtzSimpropTrigger> findAll() {
        return jdbcTemplate.query(QrtzSimpropTriggerSql.FIND_ALL, rowMapper);
    }

    @Override
    public QrtzSimpropTrigger save(QrtzSimpropTrigger entity) {
        if (existsByTriggerNameAndSchedNameAndTriggerGroup(entity.getTriggerName(), entity.getSchedName(), entity.getTriggerGroup())) {
            return update(entity);
        } else {
            return insert(entity);
        }
    }

    private QrtzSimpropTrigger insert(QrtzSimpropTrigger entity) {
        // Set audit fields if they exist
        long now = System.currentTimeMillis();

        MapSqlParameterSource params = createParameterMap(entity);
        jdbcTemplate.update(QrtzSimpropTriggerSql.INSERT, params);
        return entity;
    }

    private QrtzSimpropTrigger update(QrtzSimpropTrigger entity) {
        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(QrtzSimpropTriggerSql.UPDATE, params);
        
        if (rowsAffected == 0) {
            throw new RuntimeException("Entity not found for update");
        }
        return entity;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(QrtzSimpropTriggerSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<QrtzSimpropTrigger> findByTriggerName(Long triggerName) {
        return jdbcTemplate.query(
            QrtzSimpropTriggerSql.FIND_BY_TRIGGER_NAME,
            Map.of("triggerName", triggerName),
            rowMapper
        );
    }

    @Override
    public List<QrtzSimpropTrigger> findBySchedName(Long schedName) {
        return jdbcTemplate.query(
            QrtzSimpropTriggerSql.FIND_BY_SCHED_NAME,
            Map.of("schedName", schedName),
            rowMapper
        );
    }

    @Override
    public List<QrtzSimpropTrigger> findByTriggerGroup(Long triggerGroup) {
        return jdbcTemplate.query(
            QrtzSimpropTriggerSql.FIND_BY_TRIGGER_GROUP,
            Map.of("triggerGroup", triggerGroup),
            rowMapper
        );
    }

    private MapSqlParameterSource createParameterMap(QrtzSimpropTrigger entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("strProp3", entity.getStrProp3());
        params.addValue("strProp2", entity.getStrProp2());
        params.addValue("strProp1", entity.getStrProp1());
        params.addValue("triggerName", entity.getTriggerName());
        params.addValue("intProp1", entity.getIntProp1());
        params.addValue("triggerGroup", entity.getTriggerGroup());
        params.addValue("boolProp1", entity.getBoolProp1());
        params.addValue("boolProp2", entity.getBoolProp2());
        params.addValue("intProp2", entity.getIntProp2());
        params.addValue("decProp2", entity.getDecProp2());
        params.addValue("schedName", entity.getSchedName());
        params.addValue("decProp1", entity.getDecProp1());
        params.addValue("longProp1", entity.getLongProp1());
        params.addValue("longProp2", entity.getLongProp2());

        return params;
    }

}
