package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.UserAuditsDao;
import com.example.pojogenerator.pojos.UserAudits;
import com.example.daoGenerator.dao.mapper.UserAuditsRowMapper;
import com.example.daoGenerator.dao.sql.UserAuditsSql;

/**
 * JDBC implementation of UserAuditsDao
 * Generated by JDBC DAO Generator
 */
@Repository
public class JdbcUserAuditsDao implements UserAuditsDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final UserAuditsRowMapper rowMapper;

    public JdbcUserAuditsDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new UserAuditsRowMapper();
    }

    @Override
    public Optional<UserAudits> findById(Long id) {
        try {
            UserAudits result = jdbcTemplate.queryForObject(
                UserAuditsSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public List<UserAudits> findAll() {
        return jdbcTemplate.query(UserAuditsSql.FIND_ALL, rowMapper);
    }

    @Override
    public UserAudits save(UserAudits entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private UserAudits insert(UserAudits entity) {
        // Set audit fields
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        // Execute INSERT with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            UserAuditsSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private UserAudits update(UserAudits entity) {
        // Update audit fields
        entity.setModifiedAt(System.currentTimeMillis());

        // Execute UPDATE with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(
            UserAuditsSql.UPDATE,
            params
        );

        if (rowsAffected == 0) {
            throw new RuntimeException("Entity with id " + entity.getId() + " not found for update");
        }
        return entity;
    }

    private MapSqlParameterSource createParameterMap(UserAudits entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("severity", entity.getSeverity());
        params.addValue("organisationsId", entity.getOrganisationsId());
        params.addValue("action", entity.getAction());
        params.addValue("details", entity.getDetails());
        params.addValue("id", entity.getId());
        params.addValue("triggeredAt", entity.getTriggeredAt());
        params.addValue("facilityIds", entity.getFacilityIds());
        params.addValue("triggeredBy", entity.getTriggeredBy());

        return params;
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(UserAuditsSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            UserAuditsSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(UserAuditsSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

}
