package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.TaskMediaMappingDao;
import com.example.pojogenerator.pojos.TaskMediaMapping;
import com.example.daoGenerator.dao.mapper.TaskMediaMappingRowMapper;
import com.example.daoGenerator.dao.sql.TaskMediaMappingSql;

/**
 * JDBC implementation of TaskMediaMappingDao
 * Generated by JDBC DAO Generator
 */
@Repository
public class JdbcTaskMediaMappingDao implements TaskMediaMappingDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final TaskMediaMappingRowMapper rowMapper;

    public JdbcTaskMediaMappingDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new TaskMediaMappingRowMapper();
    }

    @Override
    public Optional<TaskMediaMapping> findById(Long id) {
        try {
            TaskMediaMapping result = jdbcTemplate.queryForObject(
                TaskMediaMappingSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public List<TaskMediaMapping> findAll() {
        return jdbcTemplate.query(TaskMediaMappingSql.FIND_ALL, rowMapper);
    }

    @Override
    public TaskMediaMapping save(TaskMediaMapping entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private TaskMediaMapping insert(TaskMediaMapping entity) {
        // Set audit fields
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        // Execute INSERT with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            TaskMediaMappingSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private TaskMediaMapping update(TaskMediaMapping entity) {
        // Update audit fields
        entity.setModifiedAt(System.currentTimeMillis());

        // Execute UPDATE with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(
            TaskMediaMappingSql.UPDATE,
            params
        );

        if (rowsAffected == 0) {
            throw new RuntimeException("Entity with id " + entity.getId() + " not found for update");
        }
        return entity;
    }

    private MapSqlParameterSource createParameterMap(TaskMediaMapping entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("createdAt", entity.getCreatedAt());
        params.addValue("mediasId", entity.getMediasId());
        params.addValue("createdBy", entity.getCreatedBy());
        params.addValue("tasksId", entity.getTasksId());
        params.addValue("modifiedAt", entity.getModifiedAt());
        params.addValue("modifiedBy", entity.getModifiedBy());

        return params;
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(TaskMediaMappingSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            TaskMediaMappingSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(TaskMediaMappingSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<TaskMediaMapping> findByTasksId(Long tasksId) {
        return jdbcTemplate.query(
            TaskMediaMappingSql.FIND_BY_TASKS_ID,
            Map.of("tasksId", tasksId),
            rowMapper
        );
    }

    @Override
    public List<TaskMediaMapping> findByModifiedBy(Long modifiedBy) {
        return jdbcTemplate.query(
            TaskMediaMappingSql.FIND_BY_MODIFIED_BY,
            Map.of("modifiedBy", modifiedBy),
            rowMapper
        );
    }

    @Override
    public List<TaskMediaMapping> findByMediasId(Long mediasId) {
        return jdbcTemplate.query(
            TaskMediaMappingSql.FIND_BY_MEDIAS_ID,
            Map.of("mediasId", mediasId),
            rowMapper
        );
    }

    @Override
    public List<TaskMediaMapping> findByCreatedBy(Long createdBy) {
        return jdbcTemplate.query(
            TaskMediaMappingSql.FIND_BY_CREATED_BY,
            Map.of("createdBy", createdBy),
            rowMapper
        );
    }

}
