package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.CodeDao;
import com.example.pojogenerator.pojos.Code;
import com.example.daoGenerator.dao.mapper.CodeRowMapper;
import com.example.daoGenerator.dao.sql.CodeSql;

/**
 * Enhanced JDBC implementation of CodeDao
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
@Repository
public class JdbcCodeDao implements CodeDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final CodeRowMapper rowMapper;

    public JdbcCodeDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new CodeRowMapper();
    }

    @Override
    public Optional<Code> findByClauseAndOrganisationsIdAndType(String clause, Long organisationsId, String type) {
        try {
            Code result = jdbcTemplate.queryForObject(
                CodeSql.FIND_BY_CLAUSE_AND_ORGANISATIONS_ID_AND_TYPE,
                Map.of("clause", clause, "organisationsId", organisationsId, "type", type),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public void deleteByClauseAndOrganisationsIdAndType(String clause, Long organisationsId, String type) {
        jdbcTemplate.update(CodeSql.DELETE_BY_CLAUSE_AND_ORGANISATIONS_ID_AND_TYPE, Map.of("clause", clause, "organisationsId", organisationsId, "type", type));
    }

    @Override
    public boolean existsByClauseAndOrganisationsIdAndType(String clause, Long organisationsId, String type) {
        Integer count = jdbcTemplate.queryForObject(
            CodeSql.EXISTS_BY_CLAUSE_AND_ORGANISATIONS_ID_AND_TYPE,
            Map.of("clause", clause, "organisationsId", organisationsId, "type", type),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public List<Code> findAll() {
        return jdbcTemplate.query(CodeSql.FIND_ALL, rowMapper);
    }

    @Override
    public Code save(Code entity) {
        if (existsByClauseAndOrganisationsIdAndType(entity.getClause(), entity.getOrganisationsId(), entity.getType())) {
            return update(entity);
        } else {
            return insert(entity);
        }
    }

    private Code insert(Code entity) {
        // Set audit fields if they exist
        long now = System.currentTimeMillis();

        MapSqlParameterSource params = createParameterMap(entity);
        jdbcTemplate.update(CodeSql.INSERT, params);
        return entity;
    }

    private Code update(Code entity) {
        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(CodeSql.UPDATE, params);
        
        if (rowsAffected == 0) {
            throw new RuntimeException("Entity not found for update");
        }
        return entity;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(CodeSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<Code> findByOrganisationsId(Long organisationsId) {
        return jdbcTemplate.query(
            CodeSql.FIND_BY_ORGANISATIONS_ID,
            Map.of("organisationsId", organisationsId),
            rowMapper
        );
    }

    private MapSqlParameterSource createParameterMap(Code entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("clause", entity.getClause());
        params.addValue("organisationsId", entity.getOrganisationsId());
        params.addValue("counter", entity.getCounter());
        params.addValue("type", entity.getType());

        return params;
    }

}
