package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.ScopeDao;
import com.example.pojogenerator.pojos.Scope;
import com.example.daoGenerator.dao.mapper.ScopeRowMapper;
import com.example.daoGenerator.dao.sql.ScopeSql;

/**
 * Enhanced JDBC implementation of ScopeDao
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
@Repository
public class JdbcScopeDao implements ScopeDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final ScopeRowMapper rowMapper;

    public JdbcScopeDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new ScopeRowMapper();
    }

    @Override
    public Optional<Scope> findById(Long id) {
        try {
            Scope result = jdbcTemplate.queryForObject(
                ScopeSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(ScopeSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            ScopeSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public List<Scope> findAll() {
        return jdbcTemplate.query(ScopeSql.FIND_ALL, rowMapper);
    }

    @Override
    public Scope save(Scope entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private Scope insert(Scope entity) {
        // Set audit fields if they exist
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            ScopeSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private Scope update(Scope entity) {
        entity.setModifiedAt(System.currentTimeMillis());

        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(ScopeSql.UPDATE, params);
        
        if (rowsAffected == 0) {
            throw new RuntimeException("Entity not found for update");
        }
        return entity;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(ScopeSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<Scope> findByModifiedBy(Long modifiedBy) {
        return jdbcTemplate.query(
            ScopeSql.FIND_BY_MODIFIED_BY,
            Map.of("modifiedBy", modifiedBy),
            rowMapper
        );
    }

    @Override
    public List<Scope> findByScopeGroupsId(Long scopeGroupsId) {
        return jdbcTemplate.query(
            ScopeSql.FIND_BY_SCOPE_GROUPS_ID,
            Map.of("scopeGroupsId", scopeGroupsId),
            rowMapper
        );
    }

    @Override
    public List<Scope> findByCreatedBy(Long createdBy) {
        return jdbcTemplate.query(
            ScopeSql.FIND_BY_CREATED_BY,
            Map.of("createdBy", createdBy),
            rowMapper
        );
    }

    private MapSqlParameterSource createParameterMap(Scope entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("createdAt", entity.getCreatedAt());
        params.addValue("archived", entity.getArchived());
        params.addValue("scopeGroupsId", entity.getScopeGroupsId());
        params.addValue("createdBy", entity.getCreatedBy());
        params.addValue("orderTree", entity.getOrderTree());
        params.addValue("modifiedAt", entity.getModifiedAt());
        params.addValue("name", entity.getName());
        params.addValue("modifiedBy", entity.getModifiedBy());
        params.addValue("id", entity.getId());

        return params;
    }

}
