package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.VariationsDao;
import com.example.pojogenerator.pojos.Variations;
import com.example.daoGenerator.dao.mapper.VariationsRowMapper;
import com.example.daoGenerator.dao.sql.VariationsSql;

/**
 * JDBC implementation of VariationsDao
 * Generated by JDBC DAO Generator
 */
@Repository
public class JdbcVariationsDao implements VariationsDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final VariationsRowMapper rowMapper;

    public JdbcVariationsDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new VariationsRowMapper();
    }

    @Override
    public Optional<Variations> findById(Long id) {
        try {
            Variations result = jdbcTemplate.queryForObject(
                VariationsSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public List<Variations> findAll() {
        return jdbcTemplate.query(VariationsSql.FIND_ALL, rowMapper);
    }

    @Override
    public Variations save(Variations entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private Variations insert(Variations entity) {
        // Set audit fields
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        // Execute INSERT with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            VariationsSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private Variations update(Variations entity) {
        // Update audit fields
        entity.setModifiedAt(System.currentTimeMillis());

        // Execute UPDATE with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(
            VariationsSql.UPDATE,
            params
        );

        if (rowsAffected == 0) {
            throw new RuntimeException("Entity with id " + entity.getId() + " not found for update");
        }
        return entity;
    }

    private MapSqlParameterSource createParameterMap(Variations entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        if (entity.getOldDetails() != null) {
            params.addValue("oldDetails", entity.getOldDetails().toString());
        } else {
            params.addValue("oldDetails", null);
        }
        params.addValue("modifiedAt", entity.getModifiedAt());
        params.addValue("description", entity.getDescription());
        if (entity.getNewDetails() != null) {
            params.addValue("newDetails", entity.getNewDetails().toString());
        } else {
            params.addValue("newDetails", null);
        }
        params.addValue("type", entity.getType());
        params.addValue("variationNumber", entity.getVariationNumber());
        params.addValue("parameterValuesId", entity.getParameterValuesId());
        params.addValue("createdAt", entity.getCreatedAt());
        params.addValue("createdBy", entity.getCreatedBy());
        params.addValue("configId", entity.getConfigId());
        params.addValue("name", entity.getName());
        params.addValue("modifiedBy", entity.getModifiedBy());
        params.addValue("id", entity.getId());
        params.addValue("jobsId", entity.getJobsId());

        return params;
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(VariationsSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            VariationsSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(VariationsSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<Variations> findByParameterValuesId(Long parameterValuesId) {
        return jdbcTemplate.query(
            VariationsSql.FIND_BY_PARAMETER_VALUES_ID,
            Map.of("parameterValuesId", parameterValuesId),
            rowMapper
        );
    }

    @Override
    public List<Variations> findByJobsId(Long jobsId) {
        return jdbcTemplate.query(
            VariationsSql.FIND_BY_JOBS_ID,
            Map.of("jobsId", jobsId),
            rowMapper
        );
    }

}
