package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.TrainedUserTasksMappingDao;
import com.example.pojogenerator.pojos.TrainedUserTasksMapping;
import com.example.daoGenerator.dao.mapper.TrainedUserTasksMappingRowMapper;
import com.example.daoGenerator.dao.sql.TrainedUserTasksMappingSql;

/**
 * Enhanced JDBC implementation of TrainedUserTasksMappingDao
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
@Repository
public class JdbcTrainedUserTasksMappingDao implements TrainedUserTasksMappingDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final TrainedUserTasksMappingRowMapper rowMapper;

    public JdbcTrainedUserTasksMappingDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new TrainedUserTasksMappingRowMapper();
    }

    @Override
    public Optional<TrainedUserTasksMapping> findById(Long id) {
        try {
            TrainedUserTasksMapping result = jdbcTemplate.queryForObject(
                TrainedUserTasksMappingSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(TrainedUserTasksMappingSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            TrainedUserTasksMappingSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public List<TrainedUserTasksMapping> findAll() {
        return jdbcTemplate.query(TrainedUserTasksMappingSql.FIND_ALL, rowMapper);
    }

    @Override
    public TrainedUserTasksMapping save(TrainedUserTasksMapping entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private TrainedUserTasksMapping insert(TrainedUserTasksMapping entity) {
        // Set audit fields if they exist
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            TrainedUserTasksMappingSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private TrainedUserTasksMapping update(TrainedUserTasksMapping entity) {
        entity.setModifiedAt(System.currentTimeMillis());

        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(TrainedUserTasksMappingSql.UPDATE, params);
        
        if (rowsAffected == 0) {
            throw new RuntimeException("Entity not found for update");
        }
        return entity;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(TrainedUserTasksMappingSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<TrainedUserTasksMapping> findByTasksId(Long tasksId) {
        return jdbcTemplate.query(
            TrainedUserTasksMappingSql.FIND_BY_TASKS_ID,
            Map.of("tasksId", tasksId),
            rowMapper
        );
    }

    @Override
    public List<TrainedUserTasksMapping> findByTrainedUsersId(Long trainedUsersId) {
        return jdbcTemplate.query(
            TrainedUserTasksMappingSql.FIND_BY_TRAINED_USERS_ID,
            Map.of("trainedUsersId", trainedUsersId),
            rowMapper
        );
    }

    private MapSqlParameterSource createParameterMap(TrainedUserTasksMapping entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("trainedUsersId", entity.getTrainedUsersId());
        params.addValue("createdAt", entity.getCreatedAt());
        params.addValue("createdBy", entity.getCreatedBy());
        params.addValue("tasksId", entity.getTasksId());
        params.addValue("modifiedAt", entity.getModifiedAt());
        params.addValue("modifiedBy", entity.getModifiedBy());
        params.addValue("id", entity.getId());

        return params;
    }

}
