package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.UserGroupDao;
import com.example.pojogenerator.pojos.UserGroup;
import com.example.daoGenerator.dao.mapper.UserGroupRowMapper;
import com.example.daoGenerator.dao.sql.UserGroupSql;

/**
 * Enhanced JDBC implementation of UserGroupDao
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
@Repository
public class JdbcUserGroupDao implements UserGroupDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final UserGroupRowMapper rowMapper;

    public JdbcUserGroupDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new UserGroupRowMapper();
    }

    @Override
    public Optional<UserGroup> findById(Long id) {
        try {
            UserGroup result = jdbcTemplate.queryForObject(
                UserGroupSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(UserGroupSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            UserGroupSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public List<UserGroup> findAll() {
        return jdbcTemplate.query(UserGroupSql.FIND_ALL, rowMapper);
    }

    @Override
    public UserGroup save(UserGroup entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private UserGroup insert(UserGroup entity) {
        // Set audit fields if they exist
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            UserGroupSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private UserGroup update(UserGroup entity) {
        entity.setModifiedAt(System.currentTimeMillis());

        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(UserGroupSql.UPDATE, params);
        
        if (rowsAffected == 0) {
            throw new RuntimeException("Entity not found for update");
        }
        return entity;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(UserGroupSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<UserGroup> findByModifiedBy(Long modifiedBy) {
        return jdbcTemplate.query(
            UserGroupSql.FIND_BY_MODIFIED_BY,
            Map.of("modifiedBy", modifiedBy),
            rowMapper
        );
    }

    @Override
    public List<UserGroup> findByFacilityId(Long facilityId) {
        return jdbcTemplate.query(
            UserGroupSql.FIND_BY_FACILITY_ID,
            Map.of("facilityId", facilityId),
            rowMapper
        );
    }

    @Override
    public List<UserGroup> findByCreatedBy(Long createdBy) {
        return jdbcTemplate.query(
            UserGroupSql.FIND_BY_CREATED_BY,
            Map.of("createdBy", createdBy),
            rowMapper
        );
    }

    private MapSqlParameterSource createParameterMap(UserGroup entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("createdAt", entity.getCreatedAt());
        params.addValue("facilityId", entity.getFacilityId());
        params.addValue("createdBy", entity.getCreatedBy());
        params.addValue("modifiedAt", entity.getModifiedAt());
        params.addValue("name", entity.getName());
        params.addValue("description", entity.getDescription());
        params.addValue("active", entity.getActive());
        params.addValue("modifiedBy", entity.getModifiedBy());
        params.addValue("id", entity.getId());

        return params;
    }

}
