package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.ClientCredentialsDao;
import com.example.pojogenerator.pojos.ClientCredentials;
import com.example.daoGenerator.dao.mapper.ClientCredentialsRowMapper;
import com.example.daoGenerator.dao.sql.ClientCredentialsSql;

/**
 * JDBC implementation of ClientCredentialsDao
 * Generated by JDBC DAO Generator
 */
@Repository
public class JdbcClientCredentialsDao implements ClientCredentialsDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final ClientCredentialsRowMapper rowMapper;

    public JdbcClientCredentialsDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new ClientCredentialsRowMapper();
    }

    @Override
    public Optional<ClientCredentials> findById(Long id) {
        try {
            ClientCredentials result = jdbcTemplate.queryForObject(
                ClientCredentialsSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public List<ClientCredentials> findAll() {
        return jdbcTemplate.query(ClientCredentialsSql.FIND_ALL, rowMapper);
    }

    @Override
    public ClientCredentials save(ClientCredentials entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private ClientCredentials insert(ClientCredentials entity) {
        // Set audit fields
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        // Execute INSERT with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            ClientCredentialsSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private ClientCredentials update(ClientCredentials entity) {
        // Update audit fields
        entity.setModifiedAt(System.currentTimeMillis());

        // Execute UPDATE with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(
            ClientCredentialsSql.UPDATE,
            params
        );

        if (rowsAffected == 0) {
            throw new RuntimeException("Entity with id " + entity.getId() + " not found for update");
        }
        return entity;
    }

    private MapSqlParameterSource createParameterMap(ClientCredentials entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("archived", entity.getArchived());
        params.addValue("clientName", entity.getClientName());
        params.addValue("clientDescription", entity.getClientDescription());
        params.addValue("clientSecret", entity.getClientSecret());
        params.addValue("id", entity.getId());

        return params;
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(ClientCredentialsSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            ClientCredentialsSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(ClientCredentialsSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

}
