package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.ChecklistPropertyValueDao;
import com.example.pojogenerator.pojos.ChecklistPropertyValue;
import com.example.daoGenerator.dao.mapper.ChecklistPropertyValueRowMapper;
import com.example.daoGenerator.dao.sql.ChecklistPropertyValueSql;

/**
 * Enhanced JDBC implementation of ChecklistPropertyValueDao
 * Key Type: COMPOSITE_KEY
 * Generated by Enhanced JDBC DAO Generator
 */
@Repository
public class JdbcChecklistPropertyValueDao implements ChecklistPropertyValueDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final ChecklistPropertyValueRowMapper rowMapper;

    public JdbcChecklistPropertyValueDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new ChecklistPropertyValueRowMapper();
    }

    @Override
    public Optional<ChecklistPropertyValue> findByFacilityUseCasePropertyMappingIdAndChecklistsId(Long facilityUseCasePropertyMappingId, Long checklistsId) {
        try {
            ChecklistPropertyValue result = jdbcTemplate.queryForObject(
                ChecklistPropertyValueSql.FIND_BY_FACILITY_USE_CASE_PROPERTY_MAPPING_ID_AND_CHECKLISTS_ID,
                Map.of("facilityUseCasePropertyMappingId", facilityUseCasePropertyMappingId, "checklistsId", checklistsId),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public void deleteByFacilityUseCasePropertyMappingIdAndChecklistsId(Long facilityUseCasePropertyMappingId, Long checklistsId) {
        jdbcTemplate.update(ChecklistPropertyValueSql.DELETE_BY_FACILITY_USE_CASE_PROPERTY_MAPPING_ID_AND_CHECKLISTS_ID, Map.of("facilityUseCasePropertyMappingId", facilityUseCasePropertyMappingId, "checklistsId", checklistsId));
    }

    @Override
    public boolean existsByFacilityUseCasePropertyMappingIdAndChecklistsId(Long facilityUseCasePropertyMappingId, Long checklistsId) {
        Integer count = jdbcTemplate.queryForObject(
            ChecklistPropertyValueSql.EXISTS_BY_FACILITY_USE_CASE_PROPERTY_MAPPING_ID_AND_CHECKLISTS_ID,
            Map.of("facilityUseCasePropertyMappingId", facilityUseCasePropertyMappingId, "checklistsId", checklistsId),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public List<ChecklistPropertyValue> findAll() {
        return jdbcTemplate.query(ChecklistPropertyValueSql.FIND_ALL, rowMapper);
    }

    @Override
    public ChecklistPropertyValue save(ChecklistPropertyValue entity) {
        if (existsByFacilityUseCasePropertyMappingIdAndChecklistsId(entity.getFacilityUseCasePropertyMappingId(), entity.getChecklistsId())) {
            return update(entity);
        } else {
            return insert(entity);
        }
    }

    private ChecklistPropertyValue insert(ChecklistPropertyValue entity) {
        // Set audit fields if they exist
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        MapSqlParameterSource params = createParameterMap(entity);
        jdbcTemplate.update(ChecklistPropertyValueSql.INSERT, params);
        return entity;
    }

    private ChecklistPropertyValue update(ChecklistPropertyValue entity) {
        entity.setModifiedAt(System.currentTimeMillis());

        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(ChecklistPropertyValueSql.UPDATE, params);
        
        if (rowsAffected == 0) {
            throw new RuntimeException("Entity not found for update");
        }
        return entity;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(ChecklistPropertyValueSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<ChecklistPropertyValue> findByChecklistsId(Long checklistsId) {
        return jdbcTemplate.query(
            ChecklistPropertyValueSql.FIND_BY_CHECKLISTS_ID,
            Map.of("checklistsId", checklistsId),
            rowMapper
        );
    }

    @Override
    public List<ChecklistPropertyValue> findByFacilityUseCasePropertyMappingId(Long facilityUseCasePropertyMappingId) {
        return jdbcTemplate.query(
            ChecklistPropertyValueSql.FIND_BY_FACILITY_USE_CASE_PROPERTY_MAPPING_ID,
            Map.of("facilityUseCasePropertyMappingId", facilityUseCasePropertyMappingId),
            rowMapper
        );
    }

    @Override
    public List<ChecklistPropertyValue> findByModifiedBy(Long modifiedBy) {
        return jdbcTemplate.query(
            ChecklistPropertyValueSql.FIND_BY_MODIFIED_BY,
            Map.of("modifiedBy", modifiedBy),
            rowMapper
        );
    }

    @Override
    public List<ChecklistPropertyValue> findByCreatedBy(Long createdBy) {
        return jdbcTemplate.query(
            ChecklistPropertyValueSql.FIND_BY_CREATED_BY,
            Map.of("createdBy", createdBy),
            rowMapper
        );
    }

    private MapSqlParameterSource createParameterMap(ChecklistPropertyValue entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("createdAt", entity.getCreatedAt());
        params.addValue("createdBy", entity.getCreatedBy());
        params.addValue("modifiedAt", entity.getModifiedAt());
        params.addValue("checklistsId", entity.getChecklistsId());
        params.addValue("modifiedBy", entity.getModifiedBy());
        params.addValue("facilityUseCasePropertyMappingId", entity.getFacilityUseCasePropertyMappingId());
        params.addValue("value", entity.getValue());

        return params;
    }

}
