package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.DatabasechangeloglockDao;
import com.example.pojogenerator.pojos.Databasechangeloglock;
import com.example.daoGenerator.dao.mapper.DatabasechangeloglockRowMapper;
import com.example.daoGenerator.dao.sql.DatabasechangeloglockSql;

/**
 * JDBC implementation of DatabasechangeloglockDao
 * Generated by JDBC DAO Generator
 */
@Repository
public class JdbcDatabasechangeloglockDao implements DatabasechangeloglockDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final DatabasechangeloglockRowMapper rowMapper;

    public JdbcDatabasechangeloglockDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new DatabasechangeloglockRowMapper();
    }

    @Override
    public Optional<Databasechangeloglock> findById(Long id) {
        try {
            Databasechangeloglock result = jdbcTemplate.queryForObject(
                DatabasechangeloglockSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public List<Databasechangeloglock> findAll() {
        return jdbcTemplate.query(DatabasechangeloglockSql.FIND_ALL, rowMapper);
    }

    @Override
    public Databasechangeloglock save(Databasechangeloglock entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private Databasechangeloglock insert(Databasechangeloglock entity) {
        // Set audit fields
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        // Execute INSERT with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            DatabasechangeloglockSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private Databasechangeloglock update(Databasechangeloglock entity) {
        // Update audit fields
        entity.setModifiedAt(System.currentTimeMillis());

        // Execute UPDATE with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(
            DatabasechangeloglockSql.UPDATE,
            params
        );

        if (rowsAffected == 0) {
            throw new RuntimeException("Entity with id " + entity.getId() + " not found for update");
        }
        return entity;
    }

    private MapSqlParameterSource createParameterMap(Databasechangeloglock entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("lockedby", entity.getLockedby());
        params.addValue("id", entity.getId());
        params.addValue("locked", entity.getLocked());
        params.addValue("lockgranted", entity.getLockgranted());

        return params;
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(DatabasechangeloglockSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            DatabasechangeloglockSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(DatabasechangeloglockSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

}
