package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.OrganisationFacilitiesMappingDao;
import com.example.pojogenerator.pojos.OrganisationFacilitiesMapping;
import com.example.daoGenerator.dao.mapper.OrganisationFacilitiesMappingRowMapper;
import com.example.daoGenerator.dao.sql.OrganisationFacilitiesMappingSql;

/**
 * JDBC implementation of OrganisationFacilitiesMappingDao
 * Generated by JDBC DAO Generator
 */
@Repository
public class JdbcOrganisationFacilitiesMappingDao implements OrganisationFacilitiesMappingDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final OrganisationFacilitiesMappingRowMapper rowMapper;

    public JdbcOrganisationFacilitiesMappingDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new OrganisationFacilitiesMappingRowMapper();
    }

    @Override
    public Optional<OrganisationFacilitiesMapping> findById(Long id) {
        try {
            OrganisationFacilitiesMapping result = jdbcTemplate.queryForObject(
                OrganisationFacilitiesMappingSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public List<OrganisationFacilitiesMapping> findAll() {
        return jdbcTemplate.query(OrganisationFacilitiesMappingSql.FIND_ALL, rowMapper);
    }

    @Override
    public OrganisationFacilitiesMapping save(OrganisationFacilitiesMapping entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private OrganisationFacilitiesMapping insert(OrganisationFacilitiesMapping entity) {
        // Set audit fields
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        // Execute INSERT with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            OrganisationFacilitiesMappingSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private OrganisationFacilitiesMapping update(OrganisationFacilitiesMapping entity) {
        // Update audit fields
        entity.setModifiedAt(System.currentTimeMillis());

        // Execute UPDATE with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(
            OrganisationFacilitiesMappingSql.UPDATE,
            params
        );

        if (rowsAffected == 0) {
            throw new RuntimeException("Entity with id " + entity.getId() + " not found for update");
        }
        return entity;
    }

    private MapSqlParameterSource createParameterMap(OrganisationFacilitiesMapping entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("createdAt", entity.getCreatedAt());
        params.addValue("facilitiesId", entity.getFacilitiesId());
        params.addValue("organisationsId", entity.getOrganisationsId());
        params.addValue("createdBy", entity.getCreatedBy());

        return params;
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(OrganisationFacilitiesMappingSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            OrganisationFacilitiesMappingSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(OrganisationFacilitiesMappingSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<OrganisationFacilitiesMapping> findByOrganisationsId(Long organisationsId) {
        return jdbcTemplate.query(
            OrganisationFacilitiesMappingSql.FIND_BY_ORGANISATIONS_ID,
            Map.of("organisationsId", organisationsId),
            rowMapper
        );
    }

    @Override
    public List<OrganisationFacilitiesMapping> findByFacilitiesId(Long facilitiesId) {
        return jdbcTemplate.query(
            OrganisationFacilitiesMappingSql.FIND_BY_FACILITIES_ID,
            Map.of("facilitiesId", facilitiesId),
            rowMapper
        );
    }

    @Override
    public List<OrganisationFacilitiesMapping> findByCreatedBy(Long createdBy) {
        return jdbcTemplate.query(
            OrganisationFacilitiesMappingSql.FIND_BY_CREATED_BY,
            Map.of("createdBy", createdBy),
            rowMapper
        );
    }

}
