package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.TrainedUserDao;
import com.example.pojogenerator.pojos.TrainedUser;
import com.example.daoGenerator.dao.mapper.TrainedUserRowMapper;
import com.example.daoGenerator.dao.sql.TrainedUserSql;

/**
 * Enhanced JDBC implementation of TrainedUserDao
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
@Repository
public class JdbcTrainedUserDao implements TrainedUserDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final TrainedUserRowMapper rowMapper;

    public JdbcTrainedUserDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new TrainedUserRowMapper();
    }

    @Override
    public Optional<TrainedUser> findById(Long id) {
        try {
            TrainedUser result = jdbcTemplate.queryForObject(
                TrainedUserSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(TrainedUserSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            TrainedUserSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public List<TrainedUser> findAll() {
        return jdbcTemplate.query(TrainedUserSql.FIND_ALL, rowMapper);
    }

    @Override
    public TrainedUser save(TrainedUser entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private TrainedUser insert(TrainedUser entity) {
        // Set audit fields if they exist
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            TrainedUserSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private TrainedUser update(TrainedUser entity) {
        entity.setModifiedAt(System.currentTimeMillis());

        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(TrainedUserSql.UPDATE, params);
        
        if (rowsAffected == 0) {
            throw new RuntimeException("Entity not found for update");
        }
        return entity;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(TrainedUserSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<TrainedUser> findByUserGroupsId(Long userGroupsId) {
        return jdbcTemplate.query(
            TrainedUserSql.FIND_BY_USER_GROUPS_ID,
            Map.of("userGroupsId", userGroupsId),
            rowMapper
        );
    }

    @Override
    public List<TrainedUser> findByChecklistsId(Long checklistsId) {
        return jdbcTemplate.query(
            TrainedUserSql.FIND_BY_CHECKLISTS_ID,
            Map.of("checklistsId", checklistsId),
            rowMapper
        );
    }

    @Override
    public List<TrainedUser> findByModifiedBy(Long modifiedBy) {
        return jdbcTemplate.query(
            TrainedUserSql.FIND_BY_MODIFIED_BY,
            Map.of("modifiedBy", modifiedBy),
            rowMapper
        );
    }

    @Override
    public List<TrainedUser> findByUsersId(Long usersId) {
        return jdbcTemplate.query(
            TrainedUserSql.FIND_BY_USERS_ID,
            Map.of("usersId", usersId),
            rowMapper
        );
    }

    @Override
    public List<TrainedUser> findByFacilitiesId(Long facilitiesId) {
        return jdbcTemplate.query(
            TrainedUserSql.FIND_BY_FACILITIES_ID,
            Map.of("facilitiesId", facilitiesId),
            rowMapper
        );
    }

    @Override
    public List<TrainedUser> findByCreatedBy(Long createdBy) {
        return jdbcTemplate.query(
            TrainedUserSql.FIND_BY_CREATED_BY,
            Map.of("createdBy", createdBy),
            rowMapper
        );
    }

    private MapSqlParameterSource createParameterMap(TrainedUser entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("createdAt", entity.getCreatedAt());
        params.addValue("facilitiesId", entity.getFacilitiesId());
        params.addValue("userGroupsId", entity.getUserGroupsId());
        params.addValue("createdBy", entity.getCreatedBy());
        params.addValue("modifiedAt", entity.getModifiedAt());
        params.addValue("usersId", entity.getUsersId());
        params.addValue("checklistsId", entity.getChecklistsId());
        params.addValue("modifiedBy", entity.getModifiedBy());
        params.addValue("id", entity.getId());

        return params;
    }

}
