package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.JobCweDetailDao;
import com.example.pojogenerator.pojos.JobCweDetail;
import com.example.daoGenerator.dao.mapper.JobCweDetailRowMapper;
import com.example.daoGenerator.dao.sql.JobCweDetailSql;

/**
 * Enhanced JDBC implementation of JobCweDetailDao
 * Key Type: SINGLE_ID
 * Generated by Enhanced JDBC DAO Generator
 */
@Repository
public class JdbcJobCweDetailDao implements JobCweDetailDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final JobCweDetailRowMapper rowMapper;

    public JdbcJobCweDetailDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new JobCweDetailRowMapper();
    }

    @Override
    public Optional<JobCweDetail> findById(Long id) {
        try {
            JobCweDetail result = jdbcTemplate.queryForObject(
                JobCweDetailSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(JobCweDetailSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            JobCweDetailSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public List<JobCweDetail> findAll() {
        return jdbcTemplate.query(JobCweDetailSql.FIND_ALL, rowMapper);
    }

    @Override
    public JobCweDetail save(JobCweDetail entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private JobCweDetail insert(JobCweDetail entity) {
        // Set audit fields if they exist
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            JobCweDetailSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private JobCweDetail update(JobCweDetail entity) {
        entity.setModifiedAt(System.currentTimeMillis());

        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(JobCweDetailSql.UPDATE, params);
        
        if (rowsAffected == 0) {
            throw new RuntimeException("Entity not found for update");
        }
        return entity;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(JobCweDetailSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<JobCweDetail> findByModifiedBy(Long modifiedBy) {
        return jdbcTemplate.query(
            JobCweDetailSql.FIND_BY_MODIFIED_BY,
            Map.of("modifiedBy", modifiedBy),
            rowMapper
        );
    }

    @Override
    public List<JobCweDetail> findByJobsId(Long jobsId) {
        return jdbcTemplate.query(
            JobCweDetailSql.FIND_BY_JOBS_ID,
            Map.of("jobsId", jobsId),
            rowMapper
        );
    }

    @Override
    public List<JobCweDetail> findByCreatedBy(Long createdBy) {
        return jdbcTemplate.query(
            JobCweDetailSql.FIND_BY_CREATED_BY,
            Map.of("createdBy", createdBy),
            rowMapper
        );
    }

    private MapSqlParameterSource createParameterMap(JobCweDetail entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("reason", entity.getReason());
        params.addValue("createdAt", entity.getCreatedAt());
        params.addValue("createdBy", entity.getCreatedBy());
        params.addValue("modifiedAt", entity.getModifiedAt());
        params.addValue("comment", entity.getComment());
        params.addValue("modifiedBy", entity.getModifiedBy());
        params.addValue("id", entity.getId());
        params.addValue("jobsId", entity.getJobsId());

        return params;
    }

}
