package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.QrtzCalendarsDao;
import com.example.pojogenerator.pojos.QrtzCalendars;
import com.example.daoGenerator.dao.mapper.QrtzCalendarsRowMapper;
import com.example.daoGenerator.dao.sql.QrtzCalendarsSql;

/**
 * JDBC implementation of QrtzCalendarsDao
 * Generated by JDBC DAO Generator
 */
@Repository
public class JdbcQrtzCalendarsDao implements QrtzCalendarsDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final QrtzCalendarsRowMapper rowMapper;

    public JdbcQrtzCalendarsDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new QrtzCalendarsRowMapper();
    }

    @Override
    public Optional<QrtzCalendars> findById(Long id) {
        try {
            QrtzCalendars result = jdbcTemplate.queryForObject(
                QrtzCalendarsSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public List<QrtzCalendars> findAll() {
        return jdbcTemplate.query(QrtzCalendarsSql.FIND_ALL, rowMapper);
    }

    @Override
    public QrtzCalendars save(QrtzCalendars entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private QrtzCalendars insert(QrtzCalendars entity) {
        // Set audit fields
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        // Execute INSERT with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            QrtzCalendarsSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private QrtzCalendars update(QrtzCalendars entity) {
        // Update audit fields
        entity.setModifiedAt(System.currentTimeMillis());

        // Execute UPDATE with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(
            QrtzCalendarsSql.UPDATE,
            params
        );

        if (rowsAffected == 0) {
            throw new RuntimeException("Entity with id " + entity.getId() + " not found for update");
        }
        return entity;
    }

    private MapSqlParameterSource createParameterMap(QrtzCalendars entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("calendar", entity.getCalendar());
        params.addValue("calendarName", entity.getCalendarName());
        params.addValue("schedName", entity.getSchedName());

        return params;
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(QrtzCalendarsSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            QrtzCalendarsSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(QrtzCalendarsSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

}
