package com.example.daoGenerator.dao.impl;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import com.example.daoGenerator.dao.interfaces.PropertiesDao;
import com.example.pojogenerator.pojos.Properties;
import com.example.daoGenerator.dao.mapper.PropertiesRowMapper;
import com.example.daoGenerator.dao.sql.PropertiesSql;

/**
 * JDBC implementation of PropertiesDao
 * Generated by JDBC DAO Generator
 */
@Repository
public class JdbcPropertiesDao implements PropertiesDao {

    private final NamedParameterJdbcTemplate jdbcTemplate;
    private final PropertiesRowMapper rowMapper;

    public JdbcPropertiesDao(NamedParameterJdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        this.rowMapper = new PropertiesRowMapper();
    }

    @Override
    public Optional<Properties> findById(Long id) {
        try {
            Properties result = jdbcTemplate.queryForObject(
                PropertiesSql.FIND_BY_ID,
                Map.of("id", id),
                rowMapper
            );
            return Optional.ofNullable(result);
        } catch (EmptyResultDataAccessException e) {
            return Optional.empty();
        }
    }

    @Override
    public List<Properties> findAll() {
        return jdbcTemplate.query(PropertiesSql.FIND_ALL, rowMapper);
    }

    @Override
    public Properties save(Properties entity) {
        if (entity.getId() == null) {
            return insert(entity);
        } else {
            return update(entity);
        }
    }

    private Properties insert(Properties entity) {
        // Set audit fields
        long now = System.currentTimeMillis();
        if (entity.getCreatedAt() == null) {
            entity.setCreatedAt(now);
        }
        entity.setModifiedAt(now);

        // Execute INSERT with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        Long generatedId = jdbcTemplate.queryForObject(
            PropertiesSql.INSERT,
            params,
            Long.class
        );
        entity.setId(generatedId);
        return entity;
    }

    private Properties update(Properties entity) {
        // Update audit fields
        entity.setModifiedAt(System.currentTimeMillis());

        // Execute UPDATE with parameter mapping
        MapSqlParameterSource params = createParameterMap(entity);
        int rowsAffected = jdbcTemplate.update(
            PropertiesSql.UPDATE,
            params
        );

        if (rowsAffected == 0) {
            throw new RuntimeException("Entity with id " + entity.getId() + " not found for update");
        }
        return entity;
    }

    private MapSqlParameterSource createParameterMap(Properties entity) {
        MapSqlParameterSource params = new MapSqlParameterSource();

        params.addValue("orderTree", entity.getOrderTree());
        params.addValue("useCasesId", entity.getUseCasesId());
        params.addValue("modifiedAt", entity.getModifiedAt());
        params.addValue("label", entity.getLabel());
        params.addValue("type", entity.getType());
        params.addValue("archived", entity.getArchived());
        params.addValue("createdAt", entity.getCreatedAt());
        params.addValue("createdBy", entity.getCreatedBy());
        params.addValue("name", entity.getName());
        params.addValue("isGlobal", entity.getIsGlobal());
        params.addValue("modifiedBy", entity.getModifiedBy());
        params.addValue("id", entity.getId());
        params.addValue("placeHolder", entity.getPlaceHolder());

        return params;
    }

    @Override
    public void deleteById(Long id) {
        jdbcTemplate.update(PropertiesSql.DELETE_BY_ID, Map.of("id", id));
    }

    @Override
    public boolean existsById(Long id) {
        Integer count = jdbcTemplate.queryForObject(
            PropertiesSql.EXISTS_BY_ID,
            Map.of("id", id),
            Integer.class
        );
        return count != null && count > 0;
    }

    @Override
    public long count() {
        Long result = jdbcTemplate.queryForObject(PropertiesSql.COUNT, Map.of(), Long.class);
        return result != null ? result : 0L;
    }

    @Override
    public List<Properties> findByUseCasesId(Long useCasesId) {
        return jdbcTemplate.query(
            PropertiesSql.FIND_BY_USE_CASES_ID,
            Map.of("useCasesId", useCasesId),
            rowMapper
        );
    }

    @Override
    public List<Properties> findByModifiedBy(Long modifiedBy) {
        return jdbcTemplate.query(
            PropertiesSql.FIND_BY_MODIFIED_BY,
            Map.of("modifiedBy", modifiedBy),
            rowMapper
        );
    }

    @Override
    public List<Properties> findByCreatedBy(Long createdBy) {
        return jdbcTemplate.query(
            PropertiesSql.FIND_BY_CREATED_BY,
            Map.of("createdBy", createdBy),
            rowMapper
        );
    }

}
