package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.ChecklistPropertyValues;

/**
 * Row mapper for ChecklistPropertyValues entity
 * Generated by JDBC DAO Generator
 */
public class ChecklistPropertyValuesRowMapper implements RowMapper<ChecklistPropertyValues> {

    @Override
    public ChecklistPropertyValues mapRow(ResultSet rs, int rowNum) throws SQLException {
        ChecklistPropertyValues entity = new ChecklistPropertyValues();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setChecklistsId(rs.getLong("checklists_id"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setFacilityUseCasePropertyMappingId(rs.getLong("facility_use_case_property_mapping_id"));
        entity.setValue(rs.getString("value"));

        return entity;
    }
}
