package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.ChecklistAudits;

/**
 * Enhanced row mapper for ChecklistAudits entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class ChecklistAuditsRowMapper implements RowMapper<ChecklistAudits> {

    @Override
    public ChecklistAudits mapRow(ResultSet rs, int rowNum) throws SQLException {
        ChecklistAudits entity = new ChecklistAudits();

        entity.setTriggeredFor(rs.getLong("triggered_for"));
        entity.setOrganisationsId(rs.getLong("organisations_id"));
        entity.setTasksId(rs.getLong("tasks_id"));
        entity.setAction(rs.getString("action"));
        entity.setChecklistsId(rs.getLong("checklists_id"));
        entity.setDetails(rs.getString("details"));
        entity.setId(rs.getLong("id"));
        entity.setTriggeredAt(rs.getLong("triggered_at"));
        entity.setStagesId(rs.getLong("stages_id"));
        entity.setTriggeredBy(rs.getLong("triggered_by"));

        return entity;
    }
}
