package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.ChecklistCollaboratorComments;

/**
 * Row mapper for ChecklistCollaboratorComments entity
 * Generated by JDBC DAO Generator
 */
public class ChecklistCollaboratorCommentsRowMapper implements RowMapper<ChecklistCollaboratorComments> {

    @Override
    public ChecklistCollaboratorComments mapRow(ResultSet rs, int rowNum) throws SQLException {
        ChecklistCollaboratorComments entity = new ChecklistCollaboratorComments();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setComments(rs.getString("comments"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setChecklistCollaboratorMappingsId(rs.getLong("checklist_collaborator_mappings_id"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setChecklistsId(rs.getLong("checklists_id"));
        entity.setId(rs.getLong("id"));
        entity.setReviewState(rs.getString("review_state"));

        return entity;
    }
}
