package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.Codes;

/**
 * Enhanced row mapper for Codes entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class CodesRowMapper implements RowMapper<Codes> {

    @Override
    public Codes mapRow(ResultSet rs, int rowNum) throws SQLException {
        Codes entity = new Codes();

        entity.setClause(rs.getString("clause"));
        entity.setOrganisationsId(rs.getLong("organisations_id"));
        entity.setCounter(rs.getInt("counter"));
        entity.setType(rs.getString("type"));

        return entity;
    }
}
