package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.Correctors;

/**
 * Enhanced row mapper for Correctors entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class CorrectorsRowMapper implements RowMapper<Correctors> {

    @Override
    public Correctors mapRow(ResultSet rs, int rowNum) throws SQLException {
        Correctors entity = new Correctors();

        entity.setCorrectionsId(rs.getLong("corrections_id"));
        entity.setActionPerformed(rs.getBoolean("action_performed"));
        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setUserGroupsId(rs.getLong("user_groups_id"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setUsersId(rs.getLong("users_id"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setId(rs.getLong("id"));

        return entity;
    }
}
