package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.FacilityUseCasePropertyMapping;

/**
 * Row mapper for FacilityUseCasePropertyMapping entity
 * Generated by JDBC DAO Generator
 */
public class FacilityUseCasePropertyMappingRowMapper implements RowMapper<FacilityUseCasePropertyMapping> {

    @Override
    public FacilityUseCasePropertyMapping mapRow(ResultSet rs, int rowNum) throws SQLException {
        FacilityUseCasePropertyMapping entity = new FacilityUseCasePropertyMapping();

        entity.setPropertiesId(rs.getLong("properties_id"));
        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setFacilitiesId(rs.getLong("facilities_id"));
        entity.setOrderTree(rs.getInt("order_tree"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setUseCasesId(rs.getLong("use_cases_id"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setLabelAlias(rs.getString("label_alias"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setId(rs.getLong("id"));
        entity.setPlaceHolderAlias(rs.getString("place_holder_alias"));
        entity.setIsMandatory(rs.getBoolean("is_mandatory"));

        return entity;
    }
}
