package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.FacilityUseCaseMapping;

/**
 * Enhanced row mapper for FacilityUseCaseMapping entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class FacilityUseCaseMappingRowMapper implements RowMapper<FacilityUseCaseMapping> {

    @Override
    public FacilityUseCaseMapping mapRow(ResultSet rs, int rowNum) throws SQLException {
        FacilityUseCaseMapping entity = new FacilityUseCaseMapping();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setFacilitiesId(rs.getLong("facilities_id"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setUseCasesId(rs.getLong("use_cases_id"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setQuota(rs.getInt("quota"));
        entity.setModifiedBy(rs.getLong("modified_by"));

        return entity;
    }
}
