package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.JobCweDetail;

/**
 * Enhanced row mapper for JobCweDetail entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class JobCweDetailRowMapper implements RowMapper<JobCweDetail> {

    @Override
    public JobCweDetail mapRow(ResultSet rs, int rowNum) throws SQLException {
        JobCweDetail entity = new JobCweDetail();

        entity.setReason(rs.getString("reason"));
        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setComment(rs.getString("comment"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setId(rs.getLong("id"));
        entity.setJobsId(rs.getLong("jobs_id"));

        return entity;
    }
}
