package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.JobCweDetailMediaMapping;

/**
 * Enhanced row mapper for JobCweDetailMediaMapping entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class JobCweDetailMediaMappingRowMapper implements RowMapper<JobCweDetailMediaMapping> {

    @Override
    public JobCweDetailMediaMapping mapRow(ResultSet rs, int rowNum) throws SQLException {
        JobCweDetailMediaMapping entity = new JobCweDetailMediaMapping();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setJobCweDetailsId(rs.getLong("job_cwe_details_id"));
        entity.setMediasId(rs.getLong("medias_id"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setModifiedBy(rs.getLong("modified_by"));

        return entity;
    }
}
