package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.JobPropertyValue;

/**
 * Enhanced row mapper for JobPropertyValue entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class JobPropertyValueRowMapper implements RowMapper<JobPropertyValue> {

    @Override
    public JobPropertyValue mapRow(ResultSet rs, int rowNum) throws SQLException {
        JobPropertyValue entity = new JobPropertyValue();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setFacilityUseCasePropertyMappingId(rs.getLong("facility_use_case_property_mapping_id"));
        entity.setValue(rs.getString("value"));
        entity.setJobsId(rs.getLong("jobs_id"));

        return entity;
    }
}
