package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.OrganisationFacilitiesMapping;

/**
 * Row mapper for OrganisationFacilitiesMapping entity
 * Generated by JDBC DAO Generator
 */
public class OrganisationFacilitiesMappingRowMapper implements RowMapper<OrganisationFacilitiesMapping> {

    @Override
    public OrganisationFacilitiesMapping mapRow(ResultSet rs, int rowNum) throws SQLException {
        OrganisationFacilitiesMapping entity = new OrganisationFacilitiesMapping();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setFacilitiesId(rs.getLong("facilities_id"));
        entity.setOrganisationsId(rs.getLong("organisations_id"));
        entity.setCreatedBy(rs.getLong("created_by"));

        return entity;
    }
}
