package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.ParameterValueApprovals;

/**
 * Enhanced row mapper for ParameterValueApprovals entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class ParameterValueApprovalsRowMapper implements RowMapper<ParameterValueApprovals> {

    @Override
    public ParameterValueApprovals mapRow(ResultSet rs, int rowNum) throws SQLException {
        ParameterValueApprovals entity = new ParameterValueApprovals();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setUsersId(rs.getLong("users_id"));
        entity.setId(rs.getLong("id"));
        entity.setState(rs.getString("state"));

        return entity;
    }
}
