package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.ParameterRuleMapping;

/**
 * Enhanced row mapper for ParameterRuleMapping entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class ParameterRuleMappingRowMapper implements RowMapper<ParameterRuleMapping> {

    @Override
    public ParameterRuleMapping mapRow(ResultSet rs, int rowNum) throws SQLException {
        ParameterRuleMapping entity = new ParameterRuleMapping();

        entity.setImpactedParametersId(rs.getLong("impacted_parameters_id"));
        entity.setTriggeringParametersId(rs.getLong("triggering_parameters_id"));
        entity.setParameterRulesId(rs.getLong("parameter_rules_id"));

        return entity;
    }
}
