package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.ParameterMediaMapping;

/**
 * Row mapper for ParameterMediaMapping entity
 * Generated by JDBC DAO Generator
 */
public class ParameterMediaMappingRowMapper implements RowMapper<ParameterMediaMapping> {

    @Override
    public ParameterMediaMapping mapRow(ResultSet rs, int rowNum) throws SQLException {
        ParameterMediaMapping entity = new ParameterMediaMapping();

        entity.setArchived(rs.getBoolean("archived"));
        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setMediasId(rs.getLong("medias_id"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setParametersId(rs.getLong("parameters_id"));

        return entity;
    }
}
