package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.PasswordHistory;

/**
 * Enhanced row mapper for PasswordHistory entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class PasswordHistoryRowMapper implements RowMapper<PasswordHistory> {

    @Override
    public PasswordHistory mapRow(ResultSet rs, int rowNum) throws SQLException {
        PasswordHistory entity = new PasswordHistory();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setPassword(rs.getString("password"));
        entity.setUsersId(rs.getLong("users_id"));
        entity.setId(rs.getLong("id"));

        return entity;
    }
}
