package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.QrtzSimpleTriggers;

/**
 * Row mapper for QrtzSimpleTriggers entity
 * Generated by JDBC DAO Generator
 */
public class QrtzSimpleTriggersRowMapper implements RowMapper<QrtzSimpleTriggers> {

    @Override
    public QrtzSimpleTriggers mapRow(ResultSet rs, int rowNum) throws SQLException {
        QrtzSimpleTriggers entity = new QrtzSimpleTriggers();

        entity.setTriggerGroup(rs.getString("trigger_group"));
        entity.setTriggerName(rs.getString("trigger_name"));
        entity.setRepeatInterval(rs.getLong("repeat_interval"));
        entity.setSchedName(rs.getString("sched_name"));
        entity.setTimesTriggered(rs.getLong("times_triggered"));
        entity.setRepeatCount(rs.getLong("repeat_count"));

        return entity;
    }
}
