package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.QrtzPausedTriggerGrps;

/**
 * Row mapper for QrtzPausedTriggerGrps entity
 * Generated by JDBC DAO Generator
 */
public class QrtzPausedTriggerGrpsRowMapper implements RowMapper<QrtzPausedTriggerGrps> {

    @Override
    public QrtzPausedTriggerGrps mapRow(ResultSet rs, int rowNum) throws SQLException {
        QrtzPausedTriggerGrps entity = new QrtzPausedTriggerGrps();

        entity.setTriggerGroup(rs.getString("trigger_group"));
        entity.setSchedName(rs.getString("sched_name"));

        return entity;
    }
}
