package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.ScopeGroups;

/**
 * Row mapper for ScopeGroups entity
 * Generated by JDBC DAO Generator
 */
public class ScopeGroupsRowMapper implements RowMapper<ScopeGroups> {

    @Override
    public ScopeGroups mapRow(ResultSet rs, int rowNum) throws SQLException {
        ScopeGroups entity = new ScopeGroups();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setArchived(rs.getBoolean("archived"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setOrderTree(rs.getInt("order_tree"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setName(rs.getString("name"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setId(rs.getLong("id"));
        entity.setServicesId(rs.getString("services_id"));

        return entity;
    }
}
