package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.TaskExecutorLock;

/**
 * Enhanced row mapper for TaskExecutorLock entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class TaskExecutorLockRowMapper implements RowMapper<TaskExecutorLock> {

    @Override
    public TaskExecutorLock mapRow(ResultSet rs, int rowNum) throws SQLException {
        TaskExecutorLock entity = new TaskExecutorLock();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setTasksId(rs.getLong("tasks_id"));
        entity.setReferencedTasksId(rs.getLong("referenced_tasks_id"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setId(rs.getLong("id"));
        entity.setLockType(rs.getString("lock_type"));

        return entity;
    }
}
