package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.TaskExecutionTimers;

/**
 * Row mapper for TaskExecutionTimers entity
 * Generated by JDBC DAO Generator
 */
public class TaskExecutionTimersRowMapper implements RowMapper<TaskExecutionTimers> {

    @Override
    public TaskExecutionTimers mapRow(ResultSet rs, int rowNum) throws SQLException {
        TaskExecutionTimers entity = new TaskExecutionTimers();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setReason(rs.getString("reason"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setResumedAt(rs.getLong("resumed_at"));
        entity.setComment(rs.getString("comment"));
        entity.setPausedAt(rs.getLong("paused_at"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setId(rs.getLong("id"));
        entity.setTaskExecutionsId(rs.getLong("task_executions_id"));

        return entity;
    }
}
