package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.TempParameterVerifications;

/**
 * Enhanced row mapper for TempParameterVerifications entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class TempParameterVerificationsRowMapper implements RowMapper<TempParameterVerifications> {

    @Override
    public TempParameterVerifications mapRow(ResultSet rs, int rowNum) throws SQLException {
        TempParameterVerifications entity = new TempParameterVerifications();

        entity.setComments(rs.getString("comments"));
        entity.setVerificationStatus(rs.getString("verification_status"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setTempParameterValuesId(rs.getLong("temp_parameter_values_id"));
        entity.setUserGroupsId(rs.getLong("user_groups_id"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setUsersId(rs.getLong("users_id"));
        entity.setVerificationType(rs.getString("verification_type"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setId(rs.getLong("id"));
        entity.setJobsId(rs.getLong("jobs_id"));
        entity.setIsBulk(rs.getBoolean("is_bulk"));

        return entity;
    }
}
