package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.TrainedUsers;

/**
 * Enhanced row mapper for TrainedUsers entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class TrainedUsersRowMapper implements RowMapper<TrainedUsers> {

    @Override
    public TrainedUsers mapRow(ResultSet rs, int rowNum) throws SQLException {
        TrainedUsers entity = new TrainedUsers();

        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setFacilitiesId(rs.getLong("facilities_id"));
        entity.setUserGroupsId(rs.getLong("user_groups_id"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setUsersId(rs.getLong("users_id"));
        entity.setChecklistsId(rs.getLong("checklists_id"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setId(rs.getLong("id"));

        return entity;
    }
}
