package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.TrainedUsersProcessPermissionsMapping;

/**
 * Enhanced row mapper for TrainedUsersProcessPermissionsMapping entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class TrainedUsersProcessPermissionsMappingRowMapper implements RowMapper<TrainedUsersProcessPermissionsMapping> {

    @Override
    public TrainedUsersProcessPermissionsMapping mapRow(ResultSet rs, int rowNum) throws SQLException {
        TrainedUsersProcessPermissionsMapping entity = new TrainedUsersProcessPermissionsMapping();

        entity.setTrainedUsersId(rs.getLong("trained_users_id"));
        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setProcessPermissionsId(rs.getLong("process_permissions_id"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setId(rs.getLong("id"));

        return entity;
    }
}
