package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.UserGroupAudits;

/**
 * Enhanced row mapper for UserGroupAudits entity
 * Generated by Enhanced JDBC DAO Generator
 */
public class UserGroupAuditsRowMapper implements RowMapper<UserGroupAudits> {

    @Override
    public UserGroupAudits mapRow(ResultSet rs, int rowNum) throws SQLException {
        UserGroupAudits entity = new UserGroupAudits();

        entity.setFacilitiesId(rs.getLong("facilities_id"));
        entity.setUserGroupsId(rs.getLong("user_groups_id"));
        entity.setOrganisationsId(rs.getLong("organisations_id"));
        entity.setDetails(rs.getString("details"));
        entity.setId(rs.getLong("id"));
        entity.setTriggeredAt(rs.getLong("triggered_at"));
        entity.setTriggeredBy(rs.getLong("triggered_by"));

        return entity;
    }
}
