package com.example.daoGenerator.dao.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import com.example.pojogenerator.pojos.Versions;

/**
 * Row mapper for Versions entity
 * Generated by JDBC DAO Generator
 */
public class VersionsRowMapper implements RowMapper<Versions> {

    @Override
    public Versions mapRow(ResultSet rs, int rowNum) throws SQLException {
        Versions entity = new Versions();

        entity.setVersionedAt(rs.getLong("versioned_at"));
        entity.setCreatedAt(rs.getLong("created_at"));
        entity.setParent(rs.getLong("parent"));
        entity.setCreatedBy(rs.getLong("created_by"));
        entity.setModifiedAt(rs.getLong("modified_at"));
        entity.setDeprecatedAt(rs.getLong("deprecated_at"));
        entity.setAncestor(rs.getLong("ancestor"));
        entity.setSelf(rs.getLong("self"));
        entity.setModifiedBy(rs.getLong("modified_by"));
        entity.setId(rs.getLong("id"));
        entity.setType(rs.getString("type"));
        entity.setVersion(rs.getInt("version"));

        return entity;
    }
}
