package com.example.pojogenerator.pojos;

import java.io.Serializable;
import java.util.Objects;
import com.fasterxml.jackson.databind.JsonNode;

/**
 * POJO class for table: exceptions
 * Generated by PostgreSQL POJO Generator
 * 
 * Table Information:
 * - Table Name: exceptions
 * - Primary Keys: id
 * 
 * Foreign Keys:
 * - parameter_values_id → parameter_values.id
 * - task_executions_id → task_executions.id
 * - facilities_id → facilities.id
 * - jobs_id → jobs.id
 */
public class Exceptions implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Database column: id
     * Type: int8 NOT NULL
     * Primary Key
     */
    private Long id;

    /**
     * Database column: code
     * Type: varchar(20) NOT NULL
     */
    private String code;

    /**
     * Database column: value
     * Type: text(2147483647)
     */
    private String value;

    /**
     * Database column: parameter_values_id
     * Type: int8 NOT NULL
     * Foreign Key → parameter_values.id
     */
    private Long parameterValuesId;

    /**
     * Database column: task_executions_id
     * Type: int8
     * Foreign Key → task_executions.id
     */
    private Long taskExecutionsId;

    /**
     * Database column: facilities_id
     * Type: int8 NOT NULL
     * Foreign Key → facilities.id
     */
    private Long facilitiesId;

    /**
     * Database column: jobs_id
     * Type: int8 NOT NULL
     * Foreign Key → jobs.id
     */
    private Long jobsId;

    /**
     * Database column: status
     * Type: varchar(50) NOT NULL
     */
    private String status;

    /**
     * Database column: initiators_reason
     * Type: text(2147483647)
     */
    private String initiatorsReason;

    /**
     * Database column: reviewers_reason
     * Type: text(2147483647)
     */
    private String reviewersReason;

    /**
     * Database column: created_by
     * Type: int8 NOT NULL
     */
    private Long createdBy;

    /**
     * Database column: created_at
     * Type: int8 NOT NULL
     */
    private Long createdAt;

    /**
     * Database column: modified_by
     * Type: int8 NOT NULL
     */
    private Long modifiedBy;

    /**
     * Database column: modified_at
     * Type: int8 NOT NULL
     */
    private Long modifiedAt;

    /**
     * Database column: previous_state
     * Type: varchar(50) DEFAULT: NULL::character varying
     */
    private String previousState;

    /**
     * Database column: reason
     * Type: varchar(255) DEFAULT: NULL::character varying
     */
    private String reason;

    /**
     * Database column: choices
     * Type: jsonb
     */
    private JsonNode choices;

    /**
     * Database column: rules_id
     * Type: text(2147483647)
     */
    private String rulesId;

    /**
     * Default constructor
     */
    public Exceptions() {
    }

    /**
     * Gets id
     * @return Long
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets id
     * @param id the value to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets code
     * @return String
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Sets code
     * @param code the value to set
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Gets value
     * @return String
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Sets value
     * @param value the value to set
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets parameter_values_id
     * @return Long
     */
    public Long getParameterValuesId() {
        return this.parameterValuesId;
    }

    /**
     * Sets parameter_values_id
     * @param parameterValuesId the value to set
     */
    public void setParameterValuesId(Long parameterValuesId) {
        this.parameterValuesId = parameterValuesId;
    }

    /**
     * Gets task_executions_id
     * @return Long
     */
    public Long getTaskExecutionsId() {
        return this.taskExecutionsId;
    }

    /**
     * Sets task_executions_id
     * @param taskExecutionsId the value to set
     */
    public void setTaskExecutionsId(Long taskExecutionsId) {
        this.taskExecutionsId = taskExecutionsId;
    }

    /**
     * Gets facilities_id
     * @return Long
     */
    public Long getFacilitiesId() {
        return this.facilitiesId;
    }

    /**
     * Sets facilities_id
     * @param facilitiesId the value to set
     */
    public void setFacilitiesId(Long facilitiesId) {
        this.facilitiesId = facilitiesId;
    }

    /**
     * Gets jobs_id
     * @return Long
     */
    public Long getJobsId() {
        return this.jobsId;
    }

    /**
     * Sets jobs_id
     * @param jobsId the value to set
     */
    public void setJobsId(Long jobsId) {
        this.jobsId = jobsId;
    }

    /**
     * Gets status
     * @return String
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Sets status
     * @param status the value to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Gets initiators_reason
     * @return String
     */
    public String getInitiatorsReason() {
        return this.initiatorsReason;
    }

    /**
     * Sets initiators_reason
     * @param initiatorsReason the value to set
     */
    public void setInitiatorsReason(String initiatorsReason) {
        this.initiatorsReason = initiatorsReason;
    }

    /**
     * Gets reviewers_reason
     * @return String
     */
    public String getReviewersReason() {
        return this.reviewersReason;
    }

    /**
     * Sets reviewers_reason
     * @param reviewersReason the value to set
     */
    public void setReviewersReason(String reviewersReason) {
        this.reviewersReason = reviewersReason;
    }

    /**
     * Gets created_by
     * @return Long
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Sets created_by
     * @param createdBy the value to set
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Gets created_at
     * @return Long
     */
    public Long getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Sets created_at
     * @param createdAt the value to set
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Gets modified_by
     * @return Long
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Sets modified_by
     * @param modifiedBy the value to set
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Gets modified_at
     * @return Long
     */
    public Long getModifiedAt() {
        return this.modifiedAt;
    }

    /**
     * Sets modified_at
     * @param modifiedAt the value to set
     */
    public void setModifiedAt(Long modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * Gets previous_state
     * @return String
     */
    public String getPreviousState() {
        return this.previousState;
    }

    /**
     * Sets previous_state
     * @param previousState the value to set
     */
    public void setPreviousState(String previousState) {
        this.previousState = previousState;
    }

    /**
     * Gets reason
     * @return String
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * Sets reason
     * @param reason the value to set
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Gets choices
     * @return JsonNode
     */
    public JsonNode getChoices() {
        return this.choices;
    }

    /**
     * Sets choices
     * @param choices the value to set
     */
    public void setChoices(JsonNode choices) {
        this.choices = choices;
    }

    /**
     * Gets rules_id
     * @return String
     */
    public String getRulesId() {
        return this.rulesId;
    }

    /**
     * Sets rules_id
     * @param rulesId the value to set
     */
    public void setRulesId(String rulesId) {
        this.rulesId = rulesId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        Exceptions other = (Exceptions) obj;
        return Objects.equals(this.id, other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.id);
    }

    @Override
    public String toString() {
        return "Exceptions{" +
                "id=" + id +
                ", code=" + code +
                ", value=" + value +
                ", parameterValuesId=" + parameterValuesId +
                ", taskExecutionsId=" + taskExecutionsId +
                ", facilitiesId=" + facilitiesId +
                ", jobsId=" + jobsId +
                ", status=" + status +
                ", initiatorsReason=" + initiatorsReason +
                ", reviewersReason=" + reviewersReason +
                ", createdBy=" + createdBy +
                ", createdAt=" + createdAt +
                ", modifiedBy=" + modifiedBy +
                ", modifiedAt=" + modifiedAt +
                ", previousState=" + previousState +
                ", reason=" + reason +
                ", choices=" + choices +
                ", rulesId=" + rulesId +
                '}';
    }
}
