package com.example.pojogenerator.pojos;

import java.io.Serializable;
import java.util.Objects;
import com.fasterxml.jackson.databind.JsonNode;

/**
 * POJO class for table: interlocks
 * Generated by PostgreSQL POJO Generator
 * 
 * Table Information:
 * - Table Name: interlocks
 * - Primary Keys: id
 * 
 * Foreign Keys:
 * - target_entity_id → tasks.id
 */
public class Interlocks implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Database column: id
     * Type: int8 NOT NULL
     * Primary Key
     */
    private Long id;

    /**
     * Database column: target_entity_id
     * Type: int8 NOT NULL
     * Foreign Key → tasks.id
     */
    private Long targetEntityId;

    /**
     * Database column: target_entity_type
     * Type: varchar(50) NOT NULL
     */
    private String targetEntityType;

    /**
     * Database column: validations
     * Type: jsonb
     */
    private JsonNode validations;

    /**
     * Database column: created_at
     * Type: int8 NOT NULL
     */
    private Long createdAt;

    /**
     * Database column: created_by
     * Type: int8 NOT NULL
     */
    private Long createdBy;

    /**
     * Database column: modified_by
     * Type: int8 NOT NULL
     */
    private Long modifiedBy;

    /**
     * Database column: modified_at
     * Type: int8 NOT NULL
     */
    private Long modifiedAt;

    /**
     * Default constructor
     */
    public Interlocks() {
    }

    /**
     * Gets id
     * @return Long
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets id
     * @param id the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setId(Long id) {
        if (id == null) {
            throw new IllegalArgumentException("id cannot be null");
        }
        this.id = id;
    }

    /**
     * Gets target_entity_id
     * @return Long
     */
    public Long getTargetEntityId() {
        return this.targetEntityId;
    }

    /**
     * Sets target_entity_id
     * @param targetEntityId the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setTargetEntityId(Long targetEntityId) {
        if (targetEntityId == null) {
            throw new IllegalArgumentException("target_entity_id cannot be null");
        }
        this.targetEntityId = targetEntityId;
    }

    /**
     * Gets target_entity_type
     * @return String
     */
    public String getTargetEntityType() {
        return this.targetEntityType;
    }

    /**
     * Sets target_entity_type
     * @param targetEntityType the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setTargetEntityType(String targetEntityType) {
        if (targetEntityType == null) {
            throw new IllegalArgumentException("target_entity_type cannot be null");
        }
        if (targetEntityType != null && targetEntityType.length() > 50) {
            throw new IllegalArgumentException("target_entity_type length cannot exceed 50 characters");
        }
        this.targetEntityType = targetEntityType;
    }

    /**
     * Gets validations
     * @return JsonNode
     */
    public JsonNode getValidations() {
        return this.validations;
    }

    /**
     * Sets validations
     * @param validations the value to set
     */
    public void setValidations(JsonNode validations) {
        this.validations = validations;
    }

    /**
     * Gets created_at
     * @return Long
     */
    public Long getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Sets created_at
     * @param createdAt the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setCreatedAt(Long createdAt) {
        if (createdAt == null) {
            throw new IllegalArgumentException("created_at cannot be null");
        }
        this.createdAt = createdAt;
    }

    /**
     * Gets created_by
     * @return Long
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Sets created_by
     * @param createdBy the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setCreatedBy(Long createdBy) {
        if (createdBy == null) {
            throw new IllegalArgumentException("created_by cannot be null");
        }
        this.createdBy = createdBy;
    }

    /**
     * Gets modified_by
     * @return Long
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Sets modified_by
     * @param modifiedBy the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setModifiedBy(Long modifiedBy) {
        if (modifiedBy == null) {
            throw new IllegalArgumentException("modified_by cannot be null");
        }
        this.modifiedBy = modifiedBy;
    }

    /**
     * Gets modified_at
     * @return Long
     */
    public Long getModifiedAt() {
        return this.modifiedAt;
    }

    /**
     * Sets modified_at
     * @param modifiedAt the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setModifiedAt(Long modifiedAt) {
        if (modifiedAt == null) {
            throw new IllegalArgumentException("modified_at cannot be null");
        }
        this.modifiedAt = modifiedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        Interlocks other = (Interlocks) obj;
        return Objects.equals(this.id, other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.id);
    }

    @Override
    public String toString() {
        return "Interlocks{" +
                "id=" + id +
                ", targetEntityId=" + targetEntityId +
                ", targetEntityType=" + targetEntityType +
                ", validations=" + validations +
                ", createdAt=" + createdAt +
                ", createdBy=" + createdBy +
                ", modifiedBy=" + modifiedBy +
                ", modifiedAt=" + modifiedAt +
                '}';
    }
}
