package com.example.pojogenerator.pojos;

import java.io.Serializable;
import java.util.Objects;

/**
 * POJO class for table: properties
 * Generated by PostgreSQL POJO Generator
 * 
 * Table Information:
 * - Table Name: properties
 * - Primary Keys: id
 * 
 * Foreign Keys:
 * - use_cases_id → use_cases.id
 * - created_by → users.id
 * - modified_by → users.id
 */
public class Propertie implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Database column: id
     * Type: int8 NOT NULL
     * Primary Key
     */
    private Long id;

    /**
     * Database column: use_cases_id
     * Type: int8
     * Foreign Key → use_cases.id
     */
    private Long useCasesId;

    /**
     * Database column: name
     * Type: varchar(255) NOT NULL
     */
    private String name;

    /**
     * Database column: label
     * Type: varchar(255) NOT NULL
     */
    private String label;

    /**
     * Database column: place_holder
     * Type: varchar(255) NOT NULL
     */
    private String placeHolder;

    /**
     * Database column: order_tree
     * Type: int4 NOT NULL DEFAULT: 1
     */
    private Integer orderTree;

    /**
     * Database column: is_global
     * Type: bool NOT NULL DEFAULT: false
     */
    private Boolean isGlobal;

    /**
     * Database column: type
     * Type: varchar(2147483647) NOT NULL
     */
    private String type;

    /**
     * Database column: archived
     * Type: bool NOT NULL DEFAULT: false
     */
    private Boolean archived;

    /**
     * Database column: created_by
     * Type: int8 NOT NULL
     * Foreign Key → users.id
     */
    private Long createdBy;

    /**
     * Database column: created_at
     * Type: int8 NOT NULL
     */
    private Long createdAt;

    /**
     * Database column: modified_by
     * Type: int8 NOT NULL
     * Foreign Key → users.id
     */
    private Long modifiedBy;

    /**
     * Database column: modified_at
     * Type: int8 NOT NULL
     */
    private Long modifiedAt;

    /**
     * Default constructor
     */
    public Propertie() {
    }

    /**
     * Gets id
     * @return Long
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets id
     * @param id the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setId(Long id) {
        if (id == null) {
            throw new IllegalArgumentException("id cannot be null");
        }
        this.id = id;
    }

    /**
     * Gets use_cases_id
     * @return Long
     */
    public Long getUseCasesId() {
        return this.useCasesId;
    }

    /**
     * Sets use_cases_id
     * @param useCasesId the value to set
     */
    public void setUseCasesId(Long useCasesId) {
        this.useCasesId = useCasesId;
    }

    /**
     * Gets name
     * @return String
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets name
     * @param name the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setName(String name) {
        if (name == null) {
            throw new IllegalArgumentException("name cannot be null");
        }
        if (name != null && name.length() > 255) {
            throw new IllegalArgumentException("name length cannot exceed 255 characters");
        }
        this.name = name;
    }

    /**
     * Gets label
     * @return String
     */
    public String getLabel() {
        return this.label;
    }

    /**
     * Sets label
     * @param label the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setLabel(String label) {
        if (label == null) {
            throw new IllegalArgumentException("label cannot be null");
        }
        if (label != null && label.length() > 255) {
            throw new IllegalArgumentException("label length cannot exceed 255 characters");
        }
        this.label = label;
    }

    /**
     * Gets place_holder
     * @return String
     */
    public String getPlaceHolder() {
        return this.placeHolder;
    }

    /**
     * Sets place_holder
     * @param placeHolder the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setPlaceHolder(String placeHolder) {
        if (placeHolder == null) {
            throw new IllegalArgumentException("place_holder cannot be null");
        }
        if (placeHolder != null && placeHolder.length() > 255) {
            throw new IllegalArgumentException("place_holder length cannot exceed 255 characters");
        }
        this.placeHolder = placeHolder;
    }

    /**
     * Gets order_tree
     * @return Integer
     */
    public Integer getOrderTree() {
        return this.orderTree;
    }

    /**
     * Sets order_tree
     * @param orderTree the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setOrderTree(Integer orderTree) {
        if (orderTree == null) {
            throw new IllegalArgumentException("order_tree cannot be null");
        }
        this.orderTree = orderTree;
    }

    /**
     * Gets is_global
     * @return Boolean
     */
    public Boolean getIsGlobal() {
        return this.isGlobal;
    }

    /**
     * Sets is_global
     * @param isGlobal the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setIsGlobal(Boolean isGlobal) {
        if (isGlobal == null) {
            throw new IllegalArgumentException("is_global cannot be null");
        }
        this.isGlobal = isGlobal;
    }

    /**
     * Gets type
     * @return String
     */
    public String getType() {
        return this.type;
    }

    /**
     * Sets type
     * @param type the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setType(String type) {
        if (type == null) {
            throw new IllegalArgumentException("type cannot be null");
        }
        if (type != null && type.length() > 2147483647) {
            throw new IllegalArgumentException("type length cannot exceed 2147483647 characters");
        }
        this.type = type;
    }

    /**
     * Gets archived
     * @return Boolean
     */
    public Boolean getArchived() {
        return this.archived;
    }

    /**
     * Sets archived
     * @param archived the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setArchived(Boolean archived) {
        if (archived == null) {
            throw new IllegalArgumentException("archived cannot be null");
        }
        this.archived = archived;
    }

    /**
     * Gets created_by
     * @return Long
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Sets created_by
     * @param createdBy the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setCreatedBy(Long createdBy) {
        if (createdBy == null) {
            throw new IllegalArgumentException("created_by cannot be null");
        }
        this.createdBy = createdBy;
    }

    /**
     * Gets created_at
     * @return Long
     */
    public Long getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Sets created_at
     * @param createdAt the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setCreatedAt(Long createdAt) {
        if (createdAt == null) {
            throw new IllegalArgumentException("created_at cannot be null");
        }
        this.createdAt = createdAt;
    }

    /**
     * Gets modified_by
     * @return Long
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Sets modified_by
     * @param modifiedBy the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setModifiedBy(Long modifiedBy) {
        if (modifiedBy == null) {
            throw new IllegalArgumentException("modified_by cannot be null");
        }
        this.modifiedBy = modifiedBy;
    }

    /**
     * Gets modified_at
     * @return Long
     */
    public Long getModifiedAt() {
        return this.modifiedAt;
    }

    /**
     * Sets modified_at
     * @param modifiedAt the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setModifiedAt(Long modifiedAt) {
        if (modifiedAt == null) {
            throw new IllegalArgumentException("modified_at cannot be null");
        }
        this.modifiedAt = modifiedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        Propertie other = (Propertie) obj;
        return Objects.equals(this.id, other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.id);
    }

    @Override
    public String toString() {
        return "Propertie{" +
                "id=" + id +
                ", useCasesId=" + useCasesId +
                ", name=" + name +
                ", label=" + label +
                ", placeHolder=" + placeHolder +
                ", orderTree=" + orderTree +
                ", isGlobal=" + isGlobal +
                ", type=" + type +
                ", archived=" + archived +
                ", createdBy=" + createdBy +
                ", createdAt=" + createdAt +
                ", modifiedBy=" + modifiedBy +
                ", modifiedAt=" + modifiedAt +
                '}';
    }
}
