package com.example.pojogenerator.pojos;

import java.io.Serializable;
import java.util.Objects;

/**
 * POJO class for table: relation_values
 * Generated by PostgreSQL POJO Generator
 * 
 * Table Information:
 * - Table Name: relation_values
 * - Primary Keys: id
 * 
 * Indexes:
 * - pkp32qjbpeex1d3zpvhx66 (UNIQUE): id
 * 
 * Foreign Keys:
 * - jobs_id → jobs.id
 * - relations_id → relations.id
 */
public class RelationValues implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Database column: id
     * Type: int8 NOT NULL
     * Primary Key
     */
    private Long id;

    /**
     * Database column: jobs_id
     * Type: int8 NOT NULL
     * Foreign Key → jobs.id
     */
    private Long jobsId;

    /**
     * Database column: relations_id
     * Type: int8 NOT NULL
     * Foreign Key → relations.id
     */
    private Long relationsId;

    /**
     * Database column: object_id
     * Type: varchar(50) NOT NULL
     */
    private String objectId;

    /**
     * Database column: object_external_id
     * Type: varchar(255) NOT NULL
     */
    private String objectExternalId;

    /**
     * Database column: collection
     * Type: varchar(255) NOT NULL
     */
    private String collection;

    /**
     * Database column: object_display_name
     * Type: varchar(255) NOT NULL
     */
    private String objectDisplayName;

    /**
     * Database column: object_type_external_id
     * Type: varchar(255) NOT NULL
     */
    private String objectTypeExternalId;

    /**
     * Database column: object_type_display_name
     * Type: varchar(255) NOT NULL
     */
    private String objectTypeDisplayName;

    /**
     * Database column: created_at
     * Type: int8 NOT NULL
     */
    private Long createdAt;

    /**
     * Database column: modified_at
     * Type: int8 NOT NULL
     */
    private Long modifiedAt;

    /**
     * Database column: created_by
     * Type: int8 NOT NULL
     */
    private Long createdBy;

    /**
     * Database column: modified_by
     * Type: int8 NOT NULL
     */
    private Long modifiedBy;

    /**
     * Default constructor
     */
    public RelationValues() {
    }

    /**
     * Gets id
     * @return Long
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets id
     * @param id the value to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets jobs_id
     * @return Long
     */
    public Long getJobsId() {
        return this.jobsId;
    }

    /**
     * Sets jobs_id
     * @param jobsId the value to set
     */
    public void setJobsId(Long jobsId) {
        this.jobsId = jobsId;
    }

    /**
     * Gets relations_id
     * @return Long
     */
    public Long getRelationsId() {
        return this.relationsId;
    }

    /**
     * Sets relations_id
     * @param relationsId the value to set
     */
    public void setRelationsId(Long relationsId) {
        this.relationsId = relationsId;
    }

    /**
     * Gets object_id
     * @return String
     */
    public String getObjectId() {
        return this.objectId;
    }

    /**
     * Sets object_id
     * @param objectId the value to set
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /**
     * Gets object_external_id
     * @return String
     */
    public String getObjectExternalId() {
        return this.objectExternalId;
    }

    /**
     * Sets object_external_id
     * @param objectExternalId the value to set
     */
    public void setObjectExternalId(String objectExternalId) {
        this.objectExternalId = objectExternalId;
    }

    /**
     * Gets collection
     * @return String
     */
    public String getCollection() {
        return this.collection;
    }

    /**
     * Sets collection
     * @param collection the value to set
     */
    public void setCollection(String collection) {
        this.collection = collection;
    }

    /**
     * Gets object_display_name
     * @return String
     */
    public String getObjectDisplayName() {
        return this.objectDisplayName;
    }

    /**
     * Sets object_display_name
     * @param objectDisplayName the value to set
     */
    public void setObjectDisplayName(String objectDisplayName) {
        this.objectDisplayName = objectDisplayName;
    }

    /**
     * Gets object_type_external_id
     * @return String
     */
    public String getObjectTypeExternalId() {
        return this.objectTypeExternalId;
    }

    /**
     * Sets object_type_external_id
     * @param objectTypeExternalId the value to set
     */
    public void setObjectTypeExternalId(String objectTypeExternalId) {
        this.objectTypeExternalId = objectTypeExternalId;
    }

    /**
     * Gets object_type_display_name
     * @return String
     */
    public String getObjectTypeDisplayName() {
        return this.objectTypeDisplayName;
    }

    /**
     * Sets object_type_display_name
     * @param objectTypeDisplayName the value to set
     */
    public void setObjectTypeDisplayName(String objectTypeDisplayName) {
        this.objectTypeDisplayName = objectTypeDisplayName;
    }

    /**
     * Gets created_at
     * @return Long
     */
    public Long getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Sets created_at
     * @param createdAt the value to set
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Gets modified_at
     * @return Long
     */
    public Long getModifiedAt() {
        return this.modifiedAt;
    }

    /**
     * Sets modified_at
     * @param modifiedAt the value to set
     */
    public void setModifiedAt(Long modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * Gets created_by
     * @return Long
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Sets created_by
     * @param createdBy the value to set
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Gets modified_by
     * @return Long
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Sets modified_by
     * @param modifiedBy the value to set
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        RelationValues other = (RelationValues) obj;
        return Objects.equals(this.id, other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.id);
    }

    @Override
    public String toString() {
        return "RelationValues{" +
                "id=" + id +
                ", jobsId=" + jobsId +
                ", relationsId=" + relationsId +
                ", objectId=" + objectId +
                ", objectExternalId=" + objectExternalId +
                ", collection=" + collection +
                ", objectDisplayName=" + objectDisplayName +
                ", objectTypeExternalId=" + objectTypeExternalId +
                ", objectTypeDisplayName=" + objectTypeDisplayName +
                ", createdAt=" + createdAt +
                ", modifiedAt=" + modifiedAt +
                ", createdBy=" + createdBy +
                ", modifiedBy=" + modifiedBy +
                '}';
    }
}
