package com.example.pojogenerator.pojos;

import java.io.Serializable;
import java.util.Objects;

/**
 * POJO class for table: task_media_mapping
 * Generated by PostgreSQL POJO Generator
 * 
 * Table Information:
 * - Table Name: task_media_mapping
 * - Primary Keys: medias_id, tasks_id
 * 
 * Indexes:
 * - idxb72231f6da6344c09b0cde50: tasks_id
 * - idx92a47f1537a8483ba1c71848: medias_id
 * 
 * Foreign Keys:
 * - medias_id → medias.id
 * - tasks_id → tasks.id
 * - created_by → users.id
 * - modified_by → users.id
 */
public class TaskMediaMapping implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Database column: medias_id
     * Type: int8 NOT NULL
     * Primary Key
     * Foreign Key → medias.id
     */
    private Long mediasId;

    /**
     * Database column: tasks_id
     * Type: int8 NOT NULL
     * Primary Key
     * Foreign Key → tasks.id
     */
    private Long tasksId;

    /**
     * Database column: created_at
     * Type: int8 NOT NULL
     */
    private Long createdAt;

    /**
     * Database column: modified_at
     * Type: int8 NOT NULL
     */
    private Long modifiedAt;

    /**
     * Database column: created_by
     * Type: int8 NOT NULL
     * Foreign Key → users.id
     */
    private Long createdBy;

    /**
     * Database column: modified_by
     * Type: int8 NOT NULL
     * Foreign Key → users.id
     */
    private Long modifiedBy;

    /**
     * Default constructor
     */
    public TaskMediaMapping() {
    }

    /**
     * Gets medias_id
     * @return Long
     */
    public Long getMediasId() {
        return this.mediasId;
    }

    /**
     * Sets medias_id
     * @param mediasId the value to set
     */
    public void setMediasId(Long mediasId) {
        this.mediasId = mediasId;
    }

    /**
     * Gets tasks_id
     * @return Long
     */
    public Long getTasksId() {
        return this.tasksId;
    }

    /**
     * Sets tasks_id
     * @param tasksId the value to set
     */
    public void setTasksId(Long tasksId) {
        this.tasksId = tasksId;
    }

    /**
     * Gets created_at
     * @return Long
     */
    public Long getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Sets created_at
     * @param createdAt the value to set
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Gets modified_at
     * @return Long
     */
    public Long getModifiedAt() {
        return this.modifiedAt;
    }

    /**
     * Sets modified_at
     * @param modifiedAt the value to set
     */
    public void setModifiedAt(Long modifiedAt) {
        this.modifiedAt = modifiedAt;
    }

    /**
     * Gets created_by
     * @return Long
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Sets created_by
     * @param createdBy the value to set
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Gets modified_by
     * @return Long
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Sets modified_by
     * @param modifiedBy the value to set
     */
    public void setModifiedBy(Long modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        TaskMediaMapping other = (TaskMediaMapping) obj;
        return Objects.equals(this.mediasId, other.mediasId) && Objects.equals(this.tasksId, other.tasksId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.mediasId, this.tasksId);
    }

    @Override
    public String toString() {
        return "TaskMediaMapping{" +
                "mediasId=" + mediasId +
                ", tasksId=" + tasksId +
                ", createdAt=" + createdAt +
                ", modifiedAt=" + modifiedAt +
                ", createdBy=" + createdBy +
                ", modifiedBy=" + modifiedBy +
                '}';
    }
}
