package com.example.pojogenerator.pojos;

import java.io.Serializable;
import java.util.Objects;

/**
 * POJO class for table: task_dependencies
 * Generated by PostgreSQL POJO Generator
 * 
 * Table Information:
 * - Table Name: task_dependencies
 * - Primary Keys: id
 * 
 * Foreign Keys:
 * - prerequisite_task_id → tasks.id
 * - dependent_task_id → tasks.id
 */
public class TaskDependencie implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Database column: id
     * Type: int8 NOT NULL
     * Primary Key
     */
    private Long id;

    /**
     * Database column: prerequisite_task_id
     * Type: int8 NOT NULL
     * Foreign Key → tasks.id
     */
    private Long prerequisiteTaskId;

    /**
     * Database column: dependent_task_id
     * Type: int8 NOT NULL
     * Foreign Key → tasks.id
     */
    private Long dependentTaskId;

    /**
     * Database column: created_by
     * Type: int8 NOT NULL
     */
    private Long createdBy;

    /**
     * Database column: created_at
     * Type: int8 NOT NULL
     */
    private Long createdAt;

    /**
     * Database column: modified_by
     * Type: int8 NOT NULL
     */
    private Long modifiedBy;

    /**
     * Database column: modified_at
     * Type: int8 NOT NULL
     */
    private Long modifiedAt;

    /**
     * Default constructor
     */
    public TaskDependencie() {
    }

    /**
     * Gets id
     * @return Long
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets id
     * @param id the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setId(Long id) {
        if (id == null) {
            throw new IllegalArgumentException("id cannot be null");
        }
        this.id = id;
    }

    /**
     * Gets prerequisite_task_id
     * @return Long
     */
    public Long getPrerequisiteTaskId() {
        return this.prerequisiteTaskId;
    }

    /**
     * Sets prerequisite_task_id
     * @param prerequisiteTaskId the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setPrerequisiteTaskId(Long prerequisiteTaskId) {
        if (prerequisiteTaskId == null) {
            throw new IllegalArgumentException("prerequisite_task_id cannot be null");
        }
        this.prerequisiteTaskId = prerequisiteTaskId;
    }

    /**
     * Gets dependent_task_id
     * @return Long
     */
    public Long getDependentTaskId() {
        return this.dependentTaskId;
    }

    /**
     * Sets dependent_task_id
     * @param dependentTaskId the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setDependentTaskId(Long dependentTaskId) {
        if (dependentTaskId == null) {
            throw new IllegalArgumentException("dependent_task_id cannot be null");
        }
        this.dependentTaskId = dependentTaskId;
    }

    /**
     * Gets created_by
     * @return Long
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Sets created_by
     * @param createdBy the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setCreatedBy(Long createdBy) {
        if (createdBy == null) {
            throw new IllegalArgumentException("created_by cannot be null");
        }
        this.createdBy = createdBy;
    }

    /**
     * Gets created_at
     * @return Long
     */
    public Long getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Sets created_at
     * @param createdAt the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setCreatedAt(Long createdAt) {
        if (createdAt == null) {
            throw new IllegalArgumentException("created_at cannot be null");
        }
        this.createdAt = createdAt;
    }

    /**
     * Gets modified_by
     * @return Long
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Sets modified_by
     * @param modifiedBy the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setModifiedBy(Long modifiedBy) {
        if (modifiedBy == null) {
            throw new IllegalArgumentException("modified_by cannot be null");
        }
        this.modifiedBy = modifiedBy;
    }

    /**
     * Gets modified_at
     * @return Long
     */
    public Long getModifiedAt() {
        return this.modifiedAt;
    }

    /**
     * Sets modified_at
     * @param modifiedAt the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setModifiedAt(Long modifiedAt) {
        if (modifiedAt == null) {
            throw new IllegalArgumentException("modified_at cannot be null");
        }
        this.modifiedAt = modifiedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        TaskDependencie other = (TaskDependencie) obj;
        return Objects.equals(this.id, other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.id);
    }

    @Override
    public String toString() {
        return "TaskDependencie{" +
                "id=" + id +
                ", prerequisiteTaskId=" + prerequisiteTaskId +
                ", dependentTaskId=" + dependentTaskId +
                ", createdBy=" + createdBy +
                ", createdAt=" + createdAt +
                ", modifiedBy=" + modifiedBy +
                ", modifiedAt=" + modifiedAt +
                '}';
    }
}
