package com.example.pojogenerator.pojos;

import java.io.Serializable;
import java.util.Objects;

/**
 * POJO class for table: variation_media_mapping
 * Generated by PostgreSQL POJO Generator
 * 
 * Table Information:
 * - Table Name: variation_media_mapping
 * - Primary Keys: medias_id, variations_id
 * 
 * Foreign Keys:
 * - medias_id → medias.id
 * - variations_id → variations.id
 * - created_by → users.id
 * - modified_by → users.id
 */
public class VariationMediaMapping implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Database column: medias_id
     * Type: int8 NOT NULL
     * Primary Key
     * Foreign Key → medias.id
     */
    private Long mediasId;

    /**
     * Database column: variations_id
     * Type: int8 NOT NULL
     * Primary Key
     * Foreign Key → variations.id
     */
    private Long variationsId;

    /**
     * Database column: archived
     * Type: bool DEFAULT: false
     */
    private Boolean archived;

    /**
     * Database column: created_at
     * Type: int8 NOT NULL
     */
    private Long createdAt;

    /**
     * Database column: modified_at
     * Type: int8 NOT NULL
     */
    private Long modifiedAt;

    /**
     * Database column: created_by
     * Type: int8 NOT NULL
     * Foreign Key → users.id
     */
    private Long createdBy;

    /**
     * Database column: modified_by
     * Type: int8 NOT NULL
     * Foreign Key → users.id
     */
    private Long modifiedBy;

    /**
     * Default constructor
     */
    public VariationMediaMapping() {
    }

    /**
     * Gets medias_id
     * @return Long
     */
    public Long getMediasId() {
        return this.mediasId;
    }

    /**
     * Sets medias_id
     * @param mediasId the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setMediasId(Long mediasId) {
        if (mediasId == null) {
            throw new IllegalArgumentException("medias_id cannot be null");
        }
        this.mediasId = mediasId;
    }

    /**
     * Gets variations_id
     * @return Long
     */
    public Long getVariationsId() {
        return this.variationsId;
    }

    /**
     * Sets variations_id
     * @param variationsId the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setVariationsId(Long variationsId) {
        if (variationsId == null) {
            throw new IllegalArgumentException("variations_id cannot be null");
        }
        this.variationsId = variationsId;
    }

    /**
     * Gets archived
     * @return Boolean
     */
    public Boolean getArchived() {
        return this.archived;
    }

    /**
     * Sets archived
     * @param archived the value to set
     */
    public void setArchived(Boolean archived) {
        this.archived = archived;
    }

    /**
     * Gets created_at
     * @return Long
     */
    public Long getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Sets created_at
     * @param createdAt the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setCreatedAt(Long createdAt) {
        if (createdAt == null) {
            throw new IllegalArgumentException("created_at cannot be null");
        }
        this.createdAt = createdAt;
    }

    /**
     * Gets modified_at
     * @return Long
     */
    public Long getModifiedAt() {
        return this.modifiedAt;
    }

    /**
     * Sets modified_at
     * @param modifiedAt the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setModifiedAt(Long modifiedAt) {
        if (modifiedAt == null) {
            throw new IllegalArgumentException("modified_at cannot be null");
        }
        this.modifiedAt = modifiedAt;
    }

    /**
     * Gets created_by
     * @return Long
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Sets created_by
     * @param createdBy the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setCreatedBy(Long createdBy) {
        if (createdBy == null) {
            throw new IllegalArgumentException("created_by cannot be null");
        }
        this.createdBy = createdBy;
    }

    /**
     * Gets modified_by
     * @return Long
     */
    public Long getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Sets modified_by
     * @param modifiedBy the value to set
     * @throws IllegalArgumentException if constraint validation fails
     */
    public void setModifiedBy(Long modifiedBy) {
        if (modifiedBy == null) {
            throw new IllegalArgumentException("modified_by cannot be null");
        }
        this.modifiedBy = modifiedBy;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        VariationMediaMapping other = (VariationMediaMapping) obj;
        return Objects.equals(this.mediasId, other.mediasId) && Objects.equals(this.variationsId, other.variationsId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.mediasId, this.variationsId);
    }

    @Override
    public String toString() {
        return "VariationMediaMapping{" +
                "mediasId=" + mediasId +
                ", variationsId=" + variationsId +
                ", archived=" + archived +
                ", createdAt=" + createdAt +
                ", modifiedAt=" + modifiedAt +
                ", createdBy=" + createdBy +
                ", modifiedBy=" + modifiedBy +
                '}';
    }
}
